// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: recom_rpc.proto

package recommender_rpc;

public interface DisposeRecommenderRespOrBuilder extends
    // @@protoc_insertion_point(interface_extends:recommender_rpc.DisposeRecommenderResp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 sessionId = 1;</code>
   */
  long getSessionId();

  /**
   * <pre>
   * "OK" or "error: X"
   * </pre>
   *
   * <code>string status = 2;</code>
   */
  java.lang.String getStatus();
  /**
   * <pre>
   * "OK" or "error: X"
   * </pre>
   *
   * <code>string status = 2;</code>
   */
  com.google.protobuf.ByteString
      getStatusBytes();
}
