// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: recom_rpc.proto

package recommender_rpc;

public interface DisposeRecommenderReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:recommender_rpc.DisposeRecommenderReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 sessionId = 1;</code>
   */
  long getSessionId();

  /**
   * <code>bool saveState = 2;</code>
   */
  boolean getSaveState();
}
