// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: recom_rpc.proto

package recommender_rpc;

/**
 * <pre>
 * The initialisation of the recommender service
 * </pre>
 *
 * Protobuf type {@code recommender_rpc.InitialisationReq}
 */
public  final class InitialisationReq extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:recommender_rpc.InitialisationReq)
    InitialisationReqOrBuilder {
private static final long serialVersionUID = 0L;
  // Use InitialisationReq.newBuilder() to construct.
  private InitialisationReq(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private InitialisationReq() {
    settingsPath_ = "";
    progLanguage_ = "";
    srcFilePath_ = "";
    srcDirPath_ = "";
    domainLabels_ = com.google.protobuf.LazyStringArrayList.EMPTY;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private InitialisationReq(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            settingsPath_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            progLanguage_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            srcFilePath_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            srcDirPath_ = s;
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
              domainLabels_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000010;
            }
            domainLabels_.add(s);
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
        domainLabels_ = domainLabels_.getUnmodifiableView();
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return recommender_rpc.RecommenderRpcProto.internal_static_recommender_rpc_InitialisationReq_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return recommender_rpc.RecommenderRpcProto.internal_static_recommender_rpc_InitialisationReq_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            recommender_rpc.InitialisationReq.class, recommender_rpc.InitialisationReq.Builder.class);
  }

  private int bitField0_;
  public static final int SETTINGS_PATH_FIELD_NUMBER = 1;
  private volatile java.lang.Object settingsPath_;
  /**
   * <pre>
   * Path to a file with settings of the recommender
   * </pre>
   *
   * <code>string settings_path = 1;</code>
   */
  public java.lang.String getSettingsPath() {
    java.lang.Object ref = settingsPath_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      settingsPath_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Path to a file with settings of the recommender
   * </pre>
   *
   * <code>string settings_path = 1;</code>
   */
  public com.google.protobuf.ByteString
      getSettingsPathBytes() {
    java.lang.Object ref = settingsPath_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      settingsPath_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PROG_LANGUAGE_FIELD_NUMBER = 2;
  private volatile java.lang.Object progLanguage_;
  /**
   * <pre>
   * Targeted prg language (python, java, ..)
   * </pre>
   *
   * <code>string prog_language = 2;</code>
   */
  public java.lang.String getProgLanguage() {
    java.lang.Object ref = progLanguage_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      progLanguage_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Targeted prg language (python, java, ..)
   * </pre>
   *
   * <code>string prog_language = 2;</code>
   */
  public com.google.protobuf.ByteString
      getProgLanguageBytes() {
    java.lang.Object ref = progLanguage_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      progLanguage_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SRC_FILE_PATH_FIELD_NUMBER = 3;
  private volatile java.lang.Object srcFilePath_;
  /**
   * <pre>
   * Path to the edited source file
   * </pre>
   *
   * <code>string src_file_path = 3;</code>
   */
  public java.lang.String getSrcFilePath() {
    java.lang.Object ref = srcFilePath_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      srcFilePath_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Path to the edited source file
   * </pre>
   *
   * <code>string src_file_path = 3;</code>
   */
  public com.google.protobuf.ByteString
      getSrcFilePathBytes() {
    java.lang.Object ref = srcFilePath_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      srcFilePath_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SRC_DIR_PATH_FIELD_NUMBER = 4;
  private volatile java.lang.Object srcDirPath_;
  /**
   * <pre>
   * Path to all sources
   * </pre>
   *
   * <code>string src_dir_path = 4;</code>
   */
  public java.lang.String getSrcDirPath() {
    java.lang.Object ref = srcDirPath_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      srcDirPath_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Path to all sources
   * </pre>
   *
   * <code>string src_dir_path = 4;</code>
   */
  public com.google.protobuf.ByteString
      getSrcDirPathBytes() {
    java.lang.Object ref = srcDirPath_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      srcDirPath_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DOMAIN_LABELS_FIELD_NUMBER = 5;
  private com.google.protobuf.LazyStringList domainLabels_;
  /**
   * <pre>
   * Optional labels for domains of the developed code (e.g. pandas, numpy, ..)
   * </pre>
   *
   * <code>repeated string domain_labels = 5;</code>
   */
  public com.google.protobuf.ProtocolStringList
      getDomainLabelsList() {
    return domainLabels_;
  }
  /**
   * <pre>
   * Optional labels for domains of the developed code (e.g. pandas, numpy, ..)
   * </pre>
   *
   * <code>repeated string domain_labels = 5;</code>
   */
  public int getDomainLabelsCount() {
    return domainLabels_.size();
  }
  /**
   * <pre>
   * Optional labels for domains of the developed code (e.g. pandas, numpy, ..)
   * </pre>
   *
   * <code>repeated string domain_labels = 5;</code>
   */
  public java.lang.String getDomainLabels(int index) {
    return domainLabels_.get(index);
  }
  /**
   * <pre>
   * Optional labels for domains of the developed code (e.g. pandas, numpy, ..)
   * </pre>
   *
   * <code>repeated string domain_labels = 5;</code>
   */
  public com.google.protobuf.ByteString
      getDomainLabelsBytes(int index) {
    return domainLabels_.getByteString(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getSettingsPathBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, settingsPath_);
    }
    if (!getProgLanguageBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, progLanguage_);
    }
    if (!getSrcFilePathBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, srcFilePath_);
    }
    if (!getSrcDirPathBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, srcDirPath_);
    }
    for (int i = 0; i < domainLabels_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, domainLabels_.getRaw(i));
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getSettingsPathBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, settingsPath_);
    }
    if (!getProgLanguageBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, progLanguage_);
    }
    if (!getSrcFilePathBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, srcFilePath_);
    }
    if (!getSrcDirPathBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, srcDirPath_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < domainLabels_.size(); i++) {
        dataSize += computeStringSizeNoTag(domainLabels_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getDomainLabelsList().size();
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof recommender_rpc.InitialisationReq)) {
      return super.equals(obj);
    }
    recommender_rpc.InitialisationReq other = (recommender_rpc.InitialisationReq) obj;

    boolean result = true;
    result = result && getSettingsPath()
        .equals(other.getSettingsPath());
    result = result && getProgLanguage()
        .equals(other.getProgLanguage());
    result = result && getSrcFilePath()
        .equals(other.getSrcFilePath());
    result = result && getSrcDirPath()
        .equals(other.getSrcDirPath());
    result = result && getDomainLabelsList()
        .equals(other.getDomainLabelsList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SETTINGS_PATH_FIELD_NUMBER;
    hash = (53 * hash) + getSettingsPath().hashCode();
    hash = (37 * hash) + PROG_LANGUAGE_FIELD_NUMBER;
    hash = (53 * hash) + getProgLanguage().hashCode();
    hash = (37 * hash) + SRC_FILE_PATH_FIELD_NUMBER;
    hash = (53 * hash) + getSrcFilePath().hashCode();
    hash = (37 * hash) + SRC_DIR_PATH_FIELD_NUMBER;
    hash = (53 * hash) + getSrcDirPath().hashCode();
    if (getDomainLabelsCount() > 0) {
      hash = (37 * hash) + DOMAIN_LABELS_FIELD_NUMBER;
      hash = (53 * hash) + getDomainLabelsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static recommender_rpc.InitialisationReq parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static recommender_rpc.InitialisationReq parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static recommender_rpc.InitialisationReq parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static recommender_rpc.InitialisationReq parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static recommender_rpc.InitialisationReq parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static recommender_rpc.InitialisationReq parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static recommender_rpc.InitialisationReq parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static recommender_rpc.InitialisationReq parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static recommender_rpc.InitialisationReq parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static recommender_rpc.InitialisationReq parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static recommender_rpc.InitialisationReq parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static recommender_rpc.InitialisationReq parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(recommender_rpc.InitialisationReq prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * The initialisation of the recommender service
   * </pre>
   *
   * Protobuf type {@code recommender_rpc.InitialisationReq}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:recommender_rpc.InitialisationReq)
      recommender_rpc.InitialisationReqOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return recommender_rpc.RecommenderRpcProto.internal_static_recommender_rpc_InitialisationReq_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return recommender_rpc.RecommenderRpcProto.internal_static_recommender_rpc_InitialisationReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              recommender_rpc.InitialisationReq.class, recommender_rpc.InitialisationReq.Builder.class);
    }

    // Construct using recommender_rpc.InitialisationReq.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      settingsPath_ = "";

      progLanguage_ = "";

      srcFilePath_ = "";

      srcDirPath_ = "";

      domainLabels_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000010);
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return recommender_rpc.RecommenderRpcProto.internal_static_recommender_rpc_InitialisationReq_descriptor;
    }

    public recommender_rpc.InitialisationReq getDefaultInstanceForType() {
      return recommender_rpc.InitialisationReq.getDefaultInstance();
    }

    public recommender_rpc.InitialisationReq build() {
      recommender_rpc.InitialisationReq result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public recommender_rpc.InitialisationReq buildPartial() {
      recommender_rpc.InitialisationReq result = new recommender_rpc.InitialisationReq(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.settingsPath_ = settingsPath_;
      result.progLanguage_ = progLanguage_;
      result.srcFilePath_ = srcFilePath_;
      result.srcDirPath_ = srcDirPath_;
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        domainLabels_ = domainLabels_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000010);
      }
      result.domainLabels_ = domainLabels_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof recommender_rpc.InitialisationReq) {
        return mergeFrom((recommender_rpc.InitialisationReq)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(recommender_rpc.InitialisationReq other) {
      if (other == recommender_rpc.InitialisationReq.getDefaultInstance()) return this;
      if (!other.getSettingsPath().isEmpty()) {
        settingsPath_ = other.settingsPath_;
        onChanged();
      }
      if (!other.getProgLanguage().isEmpty()) {
        progLanguage_ = other.progLanguage_;
        onChanged();
      }
      if (!other.getSrcFilePath().isEmpty()) {
        srcFilePath_ = other.srcFilePath_;
        onChanged();
      }
      if (!other.getSrcDirPath().isEmpty()) {
        srcDirPath_ = other.srcDirPath_;
        onChanged();
      }
      if (!other.domainLabels_.isEmpty()) {
        if (domainLabels_.isEmpty()) {
          domainLabels_ = other.domainLabels_;
          bitField0_ = (bitField0_ & ~0x00000010);
        } else {
          ensureDomainLabelsIsMutable();
          domainLabels_.addAll(other.domainLabels_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      recommender_rpc.InitialisationReq parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (recommender_rpc.InitialisationReq) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object settingsPath_ = "";
    /**
     * <pre>
     * Path to a file with settings of the recommender
     * </pre>
     *
     * <code>string settings_path = 1;</code>
     */
    public java.lang.String getSettingsPath() {
      java.lang.Object ref = settingsPath_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        settingsPath_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Path to a file with settings of the recommender
     * </pre>
     *
     * <code>string settings_path = 1;</code>
     */
    public com.google.protobuf.ByteString
        getSettingsPathBytes() {
      java.lang.Object ref = settingsPath_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        settingsPath_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Path to a file with settings of the recommender
     * </pre>
     *
     * <code>string settings_path = 1;</code>
     */
    public Builder setSettingsPath(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      settingsPath_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Path to a file with settings of the recommender
     * </pre>
     *
     * <code>string settings_path = 1;</code>
     */
    public Builder clearSettingsPath() {
      
      settingsPath_ = getDefaultInstance().getSettingsPath();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Path to a file with settings of the recommender
     * </pre>
     *
     * <code>string settings_path = 1;</code>
     */
    public Builder setSettingsPathBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      settingsPath_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object progLanguage_ = "";
    /**
     * <pre>
     * Targeted prg language (python, java, ..)
     * </pre>
     *
     * <code>string prog_language = 2;</code>
     */
    public java.lang.String getProgLanguage() {
      java.lang.Object ref = progLanguage_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        progLanguage_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Targeted prg language (python, java, ..)
     * </pre>
     *
     * <code>string prog_language = 2;</code>
     */
    public com.google.protobuf.ByteString
        getProgLanguageBytes() {
      java.lang.Object ref = progLanguage_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        progLanguage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Targeted prg language (python, java, ..)
     * </pre>
     *
     * <code>string prog_language = 2;</code>
     */
    public Builder setProgLanguage(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      progLanguage_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Targeted prg language (python, java, ..)
     * </pre>
     *
     * <code>string prog_language = 2;</code>
     */
    public Builder clearProgLanguage() {
      
      progLanguage_ = getDefaultInstance().getProgLanguage();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Targeted prg language (python, java, ..)
     * </pre>
     *
     * <code>string prog_language = 2;</code>
     */
    public Builder setProgLanguageBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      progLanguage_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object srcFilePath_ = "";
    /**
     * <pre>
     * Path to the edited source file
     * </pre>
     *
     * <code>string src_file_path = 3;</code>
     */
    public java.lang.String getSrcFilePath() {
      java.lang.Object ref = srcFilePath_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        srcFilePath_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Path to the edited source file
     * </pre>
     *
     * <code>string src_file_path = 3;</code>
     */
    public com.google.protobuf.ByteString
        getSrcFilePathBytes() {
      java.lang.Object ref = srcFilePath_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        srcFilePath_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Path to the edited source file
     * </pre>
     *
     * <code>string src_file_path = 3;</code>
     */
    public Builder setSrcFilePath(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      srcFilePath_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Path to the edited source file
     * </pre>
     *
     * <code>string src_file_path = 3;</code>
     */
    public Builder clearSrcFilePath() {
      
      srcFilePath_ = getDefaultInstance().getSrcFilePath();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Path to the edited source file
     * </pre>
     *
     * <code>string src_file_path = 3;</code>
     */
    public Builder setSrcFilePathBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      srcFilePath_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object srcDirPath_ = "";
    /**
     * <pre>
     * Path to all sources
     * </pre>
     *
     * <code>string src_dir_path = 4;</code>
     */
    public java.lang.String getSrcDirPath() {
      java.lang.Object ref = srcDirPath_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        srcDirPath_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Path to all sources
     * </pre>
     *
     * <code>string src_dir_path = 4;</code>
     */
    public com.google.protobuf.ByteString
        getSrcDirPathBytes() {
      java.lang.Object ref = srcDirPath_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        srcDirPath_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Path to all sources
     * </pre>
     *
     * <code>string src_dir_path = 4;</code>
     */
    public Builder setSrcDirPath(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      srcDirPath_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Path to all sources
     * </pre>
     *
     * <code>string src_dir_path = 4;</code>
     */
    public Builder clearSrcDirPath() {
      
      srcDirPath_ = getDefaultInstance().getSrcDirPath();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Path to all sources
     * </pre>
     *
     * <code>string src_dir_path = 4;</code>
     */
    public Builder setSrcDirPathBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      srcDirPath_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList domainLabels_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureDomainLabelsIsMutable() {
      if (!((bitField0_ & 0x00000010) == 0x00000010)) {
        domainLabels_ = new com.google.protobuf.LazyStringArrayList(domainLabels_);
        bitField0_ |= 0x00000010;
       }
    }
    /**
     * <pre>
     * Optional labels for domains of the developed code (e.g. pandas, numpy, ..)
     * </pre>
     *
     * <code>repeated string domain_labels = 5;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getDomainLabelsList() {
      return domainLabels_.getUnmodifiableView();
    }
    /**
     * <pre>
     * Optional labels for domains of the developed code (e.g. pandas, numpy, ..)
     * </pre>
     *
     * <code>repeated string domain_labels = 5;</code>
     */
    public int getDomainLabelsCount() {
      return domainLabels_.size();
    }
    /**
     * <pre>
     * Optional labels for domains of the developed code (e.g. pandas, numpy, ..)
     * </pre>
     *
     * <code>repeated string domain_labels = 5;</code>
     */
    public java.lang.String getDomainLabels(int index) {
      return domainLabels_.get(index);
    }
    /**
     * <pre>
     * Optional labels for domains of the developed code (e.g. pandas, numpy, ..)
     * </pre>
     *
     * <code>repeated string domain_labels = 5;</code>
     */
    public com.google.protobuf.ByteString
        getDomainLabelsBytes(int index) {
      return domainLabels_.getByteString(index);
    }
    /**
     * <pre>
     * Optional labels for domains of the developed code (e.g. pandas, numpy, ..)
     * </pre>
     *
     * <code>repeated string domain_labels = 5;</code>
     */
    public Builder setDomainLabels(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureDomainLabelsIsMutable();
      domainLabels_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Optional labels for domains of the developed code (e.g. pandas, numpy, ..)
     * </pre>
     *
     * <code>repeated string domain_labels = 5;</code>
     */
    public Builder addDomainLabels(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureDomainLabelsIsMutable();
      domainLabels_.add(value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Optional labels for domains of the developed code (e.g. pandas, numpy, ..)
     * </pre>
     *
     * <code>repeated string domain_labels = 5;</code>
     */
    public Builder addAllDomainLabels(
        java.lang.Iterable<java.lang.String> values) {
      ensureDomainLabelsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, domainLabels_);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Optional labels for domains of the developed code (e.g. pandas, numpy, ..)
     * </pre>
     *
     * <code>repeated string domain_labels = 5;</code>
     */
    public Builder clearDomainLabels() {
      domainLabels_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Optional labels for domains of the developed code (e.g. pandas, numpy, ..)
     * </pre>
     *
     * <code>repeated string domain_labels = 5;</code>
     */
    public Builder addDomainLabelsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureDomainLabelsIsMutable();
      domainLabels_.add(value);
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:recommender_rpc.InitialisationReq)
  }

  // @@protoc_insertion_point(class_scope:recommender_rpc.InitialisationReq)
  private static final recommender_rpc.InitialisationReq DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new recommender_rpc.InitialisationReq();
  }

  public static recommender_rpc.InitialisationReq getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<InitialisationReq>
      PARSER = new com.google.protobuf.AbstractParser<InitialisationReq>() {
    public InitialisationReq parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new InitialisationReq(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<InitialisationReq> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<InitialisationReq> getParserForType() {
    return PARSER;
  }

  public recommender_rpc.InitialisationReq getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

