// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: recom_rpc.proto

package recommender_rpc;

public interface OnNewInputReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:recommender_rpc.OnNewInputReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 sessionId = 1;</code>
   */
  long getSessionId();

  /**
   * <code>string searchText = 2;</code>
   */
  java.lang.String getSearchText();
  /**
   * <code>string searchText = 2;</code>
   */
  com.google.protobuf.ByteString
      getSearchTextBytes();

  /**
   * <code>.recommender_rpc.OnNewInputReq.ChangeType changeType = 3;</code>
   */
  int getChangeTypeValue();
  /**
   * <code>.recommender_rpc.OnNewInputReq.ChangeType changeType = 3;</code>
   */
  recommender_rpc.OnNewInputReq.ChangeType getChangeType();

  /**
   * <code>repeated .recommender_rpc.Parameter activeVariables = 10;</code>
   */
  java.util.List<recommender_rpc.Parameter> 
      getActiveVariablesList();
  /**
   * <code>repeated .recommender_rpc.Parameter activeVariables = 10;</code>
   */
  recommender_rpc.Parameter getActiveVariables(int index);
  /**
   * <code>repeated .recommender_rpc.Parameter activeVariables = 10;</code>
   */
  int getActiveVariablesCount();
  /**
   * <code>repeated .recommender_rpc.Parameter activeVariables = 10;</code>
   */
  java.util.List<? extends recommender_rpc.ParameterOrBuilder> 
      getActiveVariablesOrBuilderList();
  /**
   * <code>repeated .recommender_rpc.Parameter activeVariables = 10;</code>
   */
  recommender_rpc.ParameterOrBuilder getActiveVariablesOrBuilder(
      int index);

  /**
   * <code>.recommender_rpc.ViewerSelectionState viewerState = 20;</code>
   */
  boolean hasViewerState();
  /**
   * <code>.recommender_rpc.ViewerSelectionState viewerState = 20;</code>
   */
  recommender_rpc.ViewerSelectionState getViewerState();
  /**
   * <code>.recommender_rpc.ViewerSelectionState viewerState = 20;</code>
   */
  recommender_rpc.ViewerSelectionStateOrBuilder getViewerStateOrBuilder();

  /**
   * <code>repeated .recommender_rpc.UserFocusHint userFocusHint = 30;</code>
   */
  java.util.List<recommender_rpc.UserFocusHint> 
      getUserFocusHintList();
  /**
   * <code>repeated .recommender_rpc.UserFocusHint userFocusHint = 30;</code>
   */
  recommender_rpc.UserFocusHint getUserFocusHint(int index);
  /**
   * <code>repeated .recommender_rpc.UserFocusHint userFocusHint = 30;</code>
   */
  int getUserFocusHintCount();
  /**
   * <code>repeated .recommender_rpc.UserFocusHint userFocusHint = 30;</code>
   */
  java.util.List<? extends recommender_rpc.UserFocusHintOrBuilder> 
      getUserFocusHintOrBuilderList();
  /**
   * <code>repeated .recommender_rpc.UserFocusHint userFocusHint = 30;</code>
   */
  recommender_rpc.UserFocusHintOrBuilder getUserFocusHintOrBuilder(
      int index);
}
