// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: recom_rpc.proto

package recommender_rpc;

/**
 * Protobuf type {@code recommender_rpc.OnNewInputReq}
 */
public  final class OnNewInputReq extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:recommender_rpc.OnNewInputReq)
    OnNewInputReqOrBuilder {
private static final long serialVersionUID = 0L;
  // Use OnNewInputReq.newBuilder() to construct.
  private OnNewInputReq(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private OnNewInputReq() {
    sessionId_ = 0L;
    searchText_ = "";
    changeType_ = 0;
    activeVariables_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private OnNewInputReq(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            sessionId_ = input.readInt64();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            searchText_ = s;
            break;
          }
          case 24: {
            int rawValue = input.readEnum();

            changeType_ = rawValue;
            break;
          }
          case 82: {
            if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
              activeVariables_ = new java.util.ArrayList<recommender_rpc.Parameter>();
              mutable_bitField0_ |= 0x00000008;
            }
            activeVariables_.add(
                input.readMessage(recommender_rpc.Parameter.parser(), extensionRegistry));
            break;
          }
          case 162: {
            recommender_rpc.ViewerSelectionState.Builder subBuilder = null;
            if (viewerState_ != null) {
              subBuilder = viewerState_.toBuilder();
            }
            viewerState_ = input.readMessage(recommender_rpc.ViewerSelectionState.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(viewerState_);
              viewerState_ = subBuilder.buildPartial();
            }

            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
        activeVariables_ = java.util.Collections.unmodifiableList(activeVariables_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return recommender_rpc.RecommenderRpcProto.internal_static_recommender_rpc_OnNewInputReq_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return recommender_rpc.RecommenderRpcProto.internal_static_recommender_rpc_OnNewInputReq_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            recommender_rpc.OnNewInputReq.class, recommender_rpc.OnNewInputReq.Builder.class);
  }

  /**
   * Protobuf enum {@code recommender_rpc.OnNewInputReq.ChangeType}
   */
  public enum ChangeType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>SEARCHTEXT = 0;</code>
     */
    SEARCHTEXT(0),
    /**
     * <code>VIEWERSTATE = 1;</code>
     */
    VIEWERSTATE(1),
    /**
     * <code>PREFERENCES = 2;</code>
     */
    PREFERENCES(2),
    /**
     * <pre>
     * should force complete re-computation
     * </pre>
     *
     * <code>OTHER = 10;</code>
     */
    OTHER(10),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>SEARCHTEXT = 0;</code>
     */
    public static final int SEARCHTEXT_VALUE = 0;
    /**
     * <code>VIEWERSTATE = 1;</code>
     */
    public static final int VIEWERSTATE_VALUE = 1;
    /**
     * <code>PREFERENCES = 2;</code>
     */
    public static final int PREFERENCES_VALUE = 2;
    /**
     * <pre>
     * should force complete re-computation
     * </pre>
     *
     * <code>OTHER = 10;</code>
     */
    public static final int OTHER_VALUE = 10;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ChangeType valueOf(int value) {
      return forNumber(value);
    }

    public static ChangeType forNumber(int value) {
      switch (value) {
        case 0: return SEARCHTEXT;
        case 1: return VIEWERSTATE;
        case 2: return PREFERENCES;
        case 10: return OTHER;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ChangeType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ChangeType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ChangeType>() {
            public ChangeType findValueByNumber(int number) {
              return ChangeType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return recommender_rpc.OnNewInputReq.getDescriptor().getEnumTypes().get(0);
    }

    private static final ChangeType[] VALUES = values();

    public static ChangeType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private ChangeType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:recommender_rpc.OnNewInputReq.ChangeType)
  }

  private int bitField0_;
  public static final int SESSIONID_FIELD_NUMBER = 1;
  private long sessionId_;
  /**
   * <code>int64 sessionId = 1;</code>
   */
  public long getSessionId() {
    return sessionId_;
  }

  public static final int SEARCHTEXT_FIELD_NUMBER = 2;
  private volatile java.lang.Object searchText_;
  /**
   * <code>string searchText = 2;</code>
   */
  public java.lang.String getSearchText() {
    java.lang.Object ref = searchText_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      searchText_ = s;
      return s;
    }
  }
  /**
   * <code>string searchText = 2;</code>
   */
  public com.google.protobuf.ByteString
      getSearchTextBytes() {
    java.lang.Object ref = searchText_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      searchText_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CHANGETYPE_FIELD_NUMBER = 3;
  private int changeType_;
  /**
   * <code>.recommender_rpc.OnNewInputReq.ChangeType changeType = 3;</code>
   */
  public int getChangeTypeValue() {
    return changeType_;
  }
  /**
   * <code>.recommender_rpc.OnNewInputReq.ChangeType changeType = 3;</code>
   */
  public recommender_rpc.OnNewInputReq.ChangeType getChangeType() {
    recommender_rpc.OnNewInputReq.ChangeType result = recommender_rpc.OnNewInputReq.ChangeType.valueOf(changeType_);
    return result == null ? recommender_rpc.OnNewInputReq.ChangeType.UNRECOGNIZED : result;
  }

  public static final int ACTIVEVARIABLES_FIELD_NUMBER = 10;
  private java.util.List<recommender_rpc.Parameter> activeVariables_;
  /**
   * <code>repeated .recommender_rpc.Parameter activeVariables = 10;</code>
   */
  public java.util.List<recommender_rpc.Parameter> getActiveVariablesList() {
    return activeVariables_;
  }
  /**
   * <code>repeated .recommender_rpc.Parameter activeVariables = 10;</code>
   */
  public java.util.List<? extends recommender_rpc.ParameterOrBuilder> 
      getActiveVariablesOrBuilderList() {
    return activeVariables_;
  }
  /**
   * <code>repeated .recommender_rpc.Parameter activeVariables = 10;</code>
   */
  public int getActiveVariablesCount() {
    return activeVariables_.size();
  }
  /**
   * <code>repeated .recommender_rpc.Parameter activeVariables = 10;</code>
   */
  public recommender_rpc.Parameter getActiveVariables(int index) {
    return activeVariables_.get(index);
  }
  /**
   * <code>repeated .recommender_rpc.Parameter activeVariables = 10;</code>
   */
  public recommender_rpc.ParameterOrBuilder getActiveVariablesOrBuilder(
      int index) {
    return activeVariables_.get(index);
  }

  public static final int VIEWERSTATE_FIELD_NUMBER = 20;
  private recommender_rpc.ViewerSelectionState viewerState_;
  /**
   * <pre>
   * We might all add the prefs like preferred variables etc.
   * </pre>
   *
   * <code>.recommender_rpc.ViewerSelectionState viewerState = 20;</code>
   */
  public boolean hasViewerState() {
    return viewerState_ != null;
  }
  /**
   * <pre>
   * We might all add the prefs like preferred variables etc.
   * </pre>
   *
   * <code>.recommender_rpc.ViewerSelectionState viewerState = 20;</code>
   */
  public recommender_rpc.ViewerSelectionState getViewerState() {
    return viewerState_ == null ? recommender_rpc.ViewerSelectionState.getDefaultInstance() : viewerState_;
  }
  /**
   * <pre>
   * We might all add the prefs like preferred variables etc.
   * </pre>
   *
   * <code>.recommender_rpc.ViewerSelectionState viewerState = 20;</code>
   */
  public recommender_rpc.ViewerSelectionStateOrBuilder getViewerStateOrBuilder() {
    return getViewerState();
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (sessionId_ != 0L) {
      output.writeInt64(1, sessionId_);
    }
    if (!getSearchTextBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, searchText_);
    }
    if (changeType_ != recommender_rpc.OnNewInputReq.ChangeType.SEARCHTEXT.getNumber()) {
      output.writeEnum(3, changeType_);
    }
    for (int i = 0; i < activeVariables_.size(); i++) {
      output.writeMessage(10, activeVariables_.get(i));
    }
    if (viewerState_ != null) {
      output.writeMessage(20, getViewerState());
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (sessionId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, sessionId_);
    }
    if (!getSearchTextBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, searchText_);
    }
    if (changeType_ != recommender_rpc.OnNewInputReq.ChangeType.SEARCHTEXT.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(3, changeType_);
    }
    for (int i = 0; i < activeVariables_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(10, activeVariables_.get(i));
    }
    if (viewerState_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(20, getViewerState());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof recommender_rpc.OnNewInputReq)) {
      return super.equals(obj);
    }
    recommender_rpc.OnNewInputReq other = (recommender_rpc.OnNewInputReq) obj;

    boolean result = true;
    result = result && (getSessionId()
        == other.getSessionId());
    result = result && getSearchText()
        .equals(other.getSearchText());
    result = result && changeType_ == other.changeType_;
    result = result && getActiveVariablesList()
        .equals(other.getActiveVariablesList());
    result = result && (hasViewerState() == other.hasViewerState());
    if (hasViewerState()) {
      result = result && getViewerState()
          .equals(other.getViewerState());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SESSIONID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getSessionId());
    hash = (37 * hash) + SEARCHTEXT_FIELD_NUMBER;
    hash = (53 * hash) + getSearchText().hashCode();
    hash = (37 * hash) + CHANGETYPE_FIELD_NUMBER;
    hash = (53 * hash) + changeType_;
    if (getActiveVariablesCount() > 0) {
      hash = (37 * hash) + ACTIVEVARIABLES_FIELD_NUMBER;
      hash = (53 * hash) + getActiveVariablesList().hashCode();
    }
    if (hasViewerState()) {
      hash = (37 * hash) + VIEWERSTATE_FIELD_NUMBER;
      hash = (53 * hash) + getViewerState().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static recommender_rpc.OnNewInputReq parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static recommender_rpc.OnNewInputReq parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static recommender_rpc.OnNewInputReq parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static recommender_rpc.OnNewInputReq parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static recommender_rpc.OnNewInputReq parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static recommender_rpc.OnNewInputReq parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static recommender_rpc.OnNewInputReq parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static recommender_rpc.OnNewInputReq parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static recommender_rpc.OnNewInputReq parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static recommender_rpc.OnNewInputReq parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static recommender_rpc.OnNewInputReq parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static recommender_rpc.OnNewInputReq parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(recommender_rpc.OnNewInputReq prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code recommender_rpc.OnNewInputReq}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:recommender_rpc.OnNewInputReq)
      recommender_rpc.OnNewInputReqOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return recommender_rpc.RecommenderRpcProto.internal_static_recommender_rpc_OnNewInputReq_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return recommender_rpc.RecommenderRpcProto.internal_static_recommender_rpc_OnNewInputReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              recommender_rpc.OnNewInputReq.class, recommender_rpc.OnNewInputReq.Builder.class);
    }

    // Construct using recommender_rpc.OnNewInputReq.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getActiveVariablesFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      sessionId_ = 0L;

      searchText_ = "";

      changeType_ = 0;

      if (activeVariablesBuilder_ == null) {
        activeVariables_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
      } else {
        activeVariablesBuilder_.clear();
      }
      if (viewerStateBuilder_ == null) {
        viewerState_ = null;
      } else {
        viewerState_ = null;
        viewerStateBuilder_ = null;
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return recommender_rpc.RecommenderRpcProto.internal_static_recommender_rpc_OnNewInputReq_descriptor;
    }

    public recommender_rpc.OnNewInputReq getDefaultInstanceForType() {
      return recommender_rpc.OnNewInputReq.getDefaultInstance();
    }

    public recommender_rpc.OnNewInputReq build() {
      recommender_rpc.OnNewInputReq result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public recommender_rpc.OnNewInputReq buildPartial() {
      recommender_rpc.OnNewInputReq result = new recommender_rpc.OnNewInputReq(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.sessionId_ = sessionId_;
      result.searchText_ = searchText_;
      result.changeType_ = changeType_;
      if (activeVariablesBuilder_ == null) {
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          activeVariables_ = java.util.Collections.unmodifiableList(activeVariables_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.activeVariables_ = activeVariables_;
      } else {
        result.activeVariables_ = activeVariablesBuilder_.build();
      }
      if (viewerStateBuilder_ == null) {
        result.viewerState_ = viewerState_;
      } else {
        result.viewerState_ = viewerStateBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof recommender_rpc.OnNewInputReq) {
        return mergeFrom((recommender_rpc.OnNewInputReq)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(recommender_rpc.OnNewInputReq other) {
      if (other == recommender_rpc.OnNewInputReq.getDefaultInstance()) return this;
      if (other.getSessionId() != 0L) {
        setSessionId(other.getSessionId());
      }
      if (!other.getSearchText().isEmpty()) {
        searchText_ = other.searchText_;
        onChanged();
      }
      if (other.changeType_ != 0) {
        setChangeTypeValue(other.getChangeTypeValue());
      }
      if (activeVariablesBuilder_ == null) {
        if (!other.activeVariables_.isEmpty()) {
          if (activeVariables_.isEmpty()) {
            activeVariables_ = other.activeVariables_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureActiveVariablesIsMutable();
            activeVariables_.addAll(other.activeVariables_);
          }
          onChanged();
        }
      } else {
        if (!other.activeVariables_.isEmpty()) {
          if (activeVariablesBuilder_.isEmpty()) {
            activeVariablesBuilder_.dispose();
            activeVariablesBuilder_ = null;
            activeVariables_ = other.activeVariables_;
            bitField0_ = (bitField0_ & ~0x00000008);
            activeVariablesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getActiveVariablesFieldBuilder() : null;
          } else {
            activeVariablesBuilder_.addAllMessages(other.activeVariables_);
          }
        }
      }
      if (other.hasViewerState()) {
        mergeViewerState(other.getViewerState());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      recommender_rpc.OnNewInputReq parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (recommender_rpc.OnNewInputReq) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private long sessionId_ ;
    /**
     * <code>int64 sessionId = 1;</code>
     */
    public long getSessionId() {
      return sessionId_;
    }
    /**
     * <code>int64 sessionId = 1;</code>
     */
    public Builder setSessionId(long value) {
      
      sessionId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 sessionId = 1;</code>
     */
    public Builder clearSessionId() {
      
      sessionId_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object searchText_ = "";
    /**
     * <code>string searchText = 2;</code>
     */
    public java.lang.String getSearchText() {
      java.lang.Object ref = searchText_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        searchText_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string searchText = 2;</code>
     */
    public com.google.protobuf.ByteString
        getSearchTextBytes() {
      java.lang.Object ref = searchText_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        searchText_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string searchText = 2;</code>
     */
    public Builder setSearchText(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      searchText_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string searchText = 2;</code>
     */
    public Builder clearSearchText() {
      
      searchText_ = getDefaultInstance().getSearchText();
      onChanged();
      return this;
    }
    /**
     * <code>string searchText = 2;</code>
     */
    public Builder setSearchTextBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      searchText_ = value;
      onChanged();
      return this;
    }

    private int changeType_ = 0;
    /**
     * <code>.recommender_rpc.OnNewInputReq.ChangeType changeType = 3;</code>
     */
    public int getChangeTypeValue() {
      return changeType_;
    }
    /**
     * <code>.recommender_rpc.OnNewInputReq.ChangeType changeType = 3;</code>
     */
    public Builder setChangeTypeValue(int value) {
      changeType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.recommender_rpc.OnNewInputReq.ChangeType changeType = 3;</code>
     */
    public recommender_rpc.OnNewInputReq.ChangeType getChangeType() {
      recommender_rpc.OnNewInputReq.ChangeType result = recommender_rpc.OnNewInputReq.ChangeType.valueOf(changeType_);
      return result == null ? recommender_rpc.OnNewInputReq.ChangeType.UNRECOGNIZED : result;
    }
    /**
     * <code>.recommender_rpc.OnNewInputReq.ChangeType changeType = 3;</code>
     */
    public Builder setChangeType(recommender_rpc.OnNewInputReq.ChangeType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      changeType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.recommender_rpc.OnNewInputReq.ChangeType changeType = 3;</code>
     */
    public Builder clearChangeType() {
      
      changeType_ = 0;
      onChanged();
      return this;
    }

    private java.util.List<recommender_rpc.Parameter> activeVariables_ =
      java.util.Collections.emptyList();
    private void ensureActiveVariablesIsMutable() {
      if (!((bitField0_ & 0x00000008) == 0x00000008)) {
        activeVariables_ = new java.util.ArrayList<recommender_rpc.Parameter>(activeVariables_);
        bitField0_ |= 0x00000008;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        recommender_rpc.Parameter, recommender_rpc.Parameter.Builder, recommender_rpc.ParameterOrBuilder> activeVariablesBuilder_;

    /**
     * <code>repeated .recommender_rpc.Parameter activeVariables = 10;</code>
     */
    public java.util.List<recommender_rpc.Parameter> getActiveVariablesList() {
      if (activeVariablesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(activeVariables_);
      } else {
        return activeVariablesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .recommender_rpc.Parameter activeVariables = 10;</code>
     */
    public int getActiveVariablesCount() {
      if (activeVariablesBuilder_ == null) {
        return activeVariables_.size();
      } else {
        return activeVariablesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .recommender_rpc.Parameter activeVariables = 10;</code>
     */
    public recommender_rpc.Parameter getActiveVariables(int index) {
      if (activeVariablesBuilder_ == null) {
        return activeVariables_.get(index);
      } else {
        return activeVariablesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .recommender_rpc.Parameter activeVariables = 10;</code>
     */
    public Builder setActiveVariables(
        int index, recommender_rpc.Parameter value) {
      if (activeVariablesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureActiveVariablesIsMutable();
        activeVariables_.set(index, value);
        onChanged();
      } else {
        activeVariablesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .recommender_rpc.Parameter activeVariables = 10;</code>
     */
    public Builder setActiveVariables(
        int index, recommender_rpc.Parameter.Builder builderForValue) {
      if (activeVariablesBuilder_ == null) {
        ensureActiveVariablesIsMutable();
        activeVariables_.set(index, builderForValue.build());
        onChanged();
      } else {
        activeVariablesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .recommender_rpc.Parameter activeVariables = 10;</code>
     */
    public Builder addActiveVariables(recommender_rpc.Parameter value) {
      if (activeVariablesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureActiveVariablesIsMutable();
        activeVariables_.add(value);
        onChanged();
      } else {
        activeVariablesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .recommender_rpc.Parameter activeVariables = 10;</code>
     */
    public Builder addActiveVariables(
        int index, recommender_rpc.Parameter value) {
      if (activeVariablesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureActiveVariablesIsMutable();
        activeVariables_.add(index, value);
        onChanged();
      } else {
        activeVariablesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .recommender_rpc.Parameter activeVariables = 10;</code>
     */
    public Builder addActiveVariables(
        recommender_rpc.Parameter.Builder builderForValue) {
      if (activeVariablesBuilder_ == null) {
        ensureActiveVariablesIsMutable();
        activeVariables_.add(builderForValue.build());
        onChanged();
      } else {
        activeVariablesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .recommender_rpc.Parameter activeVariables = 10;</code>
     */
    public Builder addActiveVariables(
        int index, recommender_rpc.Parameter.Builder builderForValue) {
      if (activeVariablesBuilder_ == null) {
        ensureActiveVariablesIsMutable();
        activeVariables_.add(index, builderForValue.build());
        onChanged();
      } else {
        activeVariablesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .recommender_rpc.Parameter activeVariables = 10;</code>
     */
    public Builder addAllActiveVariables(
        java.lang.Iterable<? extends recommender_rpc.Parameter> values) {
      if (activeVariablesBuilder_ == null) {
        ensureActiveVariablesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, activeVariables_);
        onChanged();
      } else {
        activeVariablesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .recommender_rpc.Parameter activeVariables = 10;</code>
     */
    public Builder clearActiveVariables() {
      if (activeVariablesBuilder_ == null) {
        activeVariables_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
      } else {
        activeVariablesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .recommender_rpc.Parameter activeVariables = 10;</code>
     */
    public Builder removeActiveVariables(int index) {
      if (activeVariablesBuilder_ == null) {
        ensureActiveVariablesIsMutable();
        activeVariables_.remove(index);
        onChanged();
      } else {
        activeVariablesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .recommender_rpc.Parameter activeVariables = 10;</code>
     */
    public recommender_rpc.Parameter.Builder getActiveVariablesBuilder(
        int index) {
      return getActiveVariablesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .recommender_rpc.Parameter activeVariables = 10;</code>
     */
    public recommender_rpc.ParameterOrBuilder getActiveVariablesOrBuilder(
        int index) {
      if (activeVariablesBuilder_ == null) {
        return activeVariables_.get(index);  } else {
        return activeVariablesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .recommender_rpc.Parameter activeVariables = 10;</code>
     */
    public java.util.List<? extends recommender_rpc.ParameterOrBuilder> 
         getActiveVariablesOrBuilderList() {
      if (activeVariablesBuilder_ != null) {
        return activeVariablesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(activeVariables_);
      }
    }
    /**
     * <code>repeated .recommender_rpc.Parameter activeVariables = 10;</code>
     */
    public recommender_rpc.Parameter.Builder addActiveVariablesBuilder() {
      return getActiveVariablesFieldBuilder().addBuilder(
          recommender_rpc.Parameter.getDefaultInstance());
    }
    /**
     * <code>repeated .recommender_rpc.Parameter activeVariables = 10;</code>
     */
    public recommender_rpc.Parameter.Builder addActiveVariablesBuilder(
        int index) {
      return getActiveVariablesFieldBuilder().addBuilder(
          index, recommender_rpc.Parameter.getDefaultInstance());
    }
    /**
     * <code>repeated .recommender_rpc.Parameter activeVariables = 10;</code>
     */
    public java.util.List<recommender_rpc.Parameter.Builder> 
         getActiveVariablesBuilderList() {
      return getActiveVariablesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        recommender_rpc.Parameter, recommender_rpc.Parameter.Builder, recommender_rpc.ParameterOrBuilder> 
        getActiveVariablesFieldBuilder() {
      if (activeVariablesBuilder_ == null) {
        activeVariablesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            recommender_rpc.Parameter, recommender_rpc.Parameter.Builder, recommender_rpc.ParameterOrBuilder>(
                activeVariables_,
                ((bitField0_ & 0x00000008) == 0x00000008),
                getParentForChildren(),
                isClean());
        activeVariables_ = null;
      }
      return activeVariablesBuilder_;
    }

    private recommender_rpc.ViewerSelectionState viewerState_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        recommender_rpc.ViewerSelectionState, recommender_rpc.ViewerSelectionState.Builder, recommender_rpc.ViewerSelectionStateOrBuilder> viewerStateBuilder_;
    /**
     * <pre>
     * We might all add the prefs like preferred variables etc.
     * </pre>
     *
     * <code>.recommender_rpc.ViewerSelectionState viewerState = 20;</code>
     */
    public boolean hasViewerState() {
      return viewerStateBuilder_ != null || viewerState_ != null;
    }
    /**
     * <pre>
     * We might all add the prefs like preferred variables etc.
     * </pre>
     *
     * <code>.recommender_rpc.ViewerSelectionState viewerState = 20;</code>
     */
    public recommender_rpc.ViewerSelectionState getViewerState() {
      if (viewerStateBuilder_ == null) {
        return viewerState_ == null ? recommender_rpc.ViewerSelectionState.getDefaultInstance() : viewerState_;
      } else {
        return viewerStateBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * We might all add the prefs like preferred variables etc.
     * </pre>
     *
     * <code>.recommender_rpc.ViewerSelectionState viewerState = 20;</code>
     */
    public Builder setViewerState(recommender_rpc.ViewerSelectionState value) {
      if (viewerStateBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        viewerState_ = value;
        onChanged();
      } else {
        viewerStateBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * We might all add the prefs like preferred variables etc.
     * </pre>
     *
     * <code>.recommender_rpc.ViewerSelectionState viewerState = 20;</code>
     */
    public Builder setViewerState(
        recommender_rpc.ViewerSelectionState.Builder builderForValue) {
      if (viewerStateBuilder_ == null) {
        viewerState_ = builderForValue.build();
        onChanged();
      } else {
        viewerStateBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * We might all add the prefs like preferred variables etc.
     * </pre>
     *
     * <code>.recommender_rpc.ViewerSelectionState viewerState = 20;</code>
     */
    public Builder mergeViewerState(recommender_rpc.ViewerSelectionState value) {
      if (viewerStateBuilder_ == null) {
        if (viewerState_ != null) {
          viewerState_ =
            recommender_rpc.ViewerSelectionState.newBuilder(viewerState_).mergeFrom(value).buildPartial();
        } else {
          viewerState_ = value;
        }
        onChanged();
      } else {
        viewerStateBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * We might all add the prefs like preferred variables etc.
     * </pre>
     *
     * <code>.recommender_rpc.ViewerSelectionState viewerState = 20;</code>
     */
    public Builder clearViewerState() {
      if (viewerStateBuilder_ == null) {
        viewerState_ = null;
        onChanged();
      } else {
        viewerState_ = null;
        viewerStateBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * We might all add the prefs like preferred variables etc.
     * </pre>
     *
     * <code>.recommender_rpc.ViewerSelectionState viewerState = 20;</code>
     */
    public recommender_rpc.ViewerSelectionState.Builder getViewerStateBuilder() {
      
      onChanged();
      return getViewerStateFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * We might all add the prefs like preferred variables etc.
     * </pre>
     *
     * <code>.recommender_rpc.ViewerSelectionState viewerState = 20;</code>
     */
    public recommender_rpc.ViewerSelectionStateOrBuilder getViewerStateOrBuilder() {
      if (viewerStateBuilder_ != null) {
        return viewerStateBuilder_.getMessageOrBuilder();
      } else {
        return viewerState_ == null ?
            recommender_rpc.ViewerSelectionState.getDefaultInstance() : viewerState_;
      }
    }
    /**
     * <pre>
     * We might all add the prefs like preferred variables etc.
     * </pre>
     *
     * <code>.recommender_rpc.ViewerSelectionState viewerState = 20;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        recommender_rpc.ViewerSelectionState, recommender_rpc.ViewerSelectionState.Builder, recommender_rpc.ViewerSelectionStateOrBuilder> 
        getViewerStateFieldBuilder() {
      if (viewerStateBuilder_ == null) {
        viewerStateBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            recommender_rpc.ViewerSelectionState, recommender_rpc.ViewerSelectionState.Builder, recommender_rpc.ViewerSelectionStateOrBuilder>(
                getViewerState(),
                getParentForChildren(),
                isClean());
        viewerState_ = null;
      }
      return viewerStateBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:recommender_rpc.OnNewInputReq)
  }

  // @@protoc_insertion_point(class_scope:recommender_rpc.OnNewInputReq)
  private static final recommender_rpc.OnNewInputReq DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new recommender_rpc.OnNewInputReq();
  }

  public static recommender_rpc.OnNewInputReq getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<OnNewInputReq>
      PARSER = new com.google.protobuf.AbstractParser<OnNewInputReq>() {
    public OnNewInputReq parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new OnNewInputReq(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<OnNewInputReq> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<OnNewInputReq> getParserForType() {
    return PARSER;
  }

  public recommender_rpc.OnNewInputReq getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

