// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: recom_rpc.proto

package recommender_rpc;

public interface OnSuggestionSelectedReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:recommender_rpc.OnSuggestionSelectedReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * todo
   * </pre>
   *
   * <code>int64 sessionId = 1;</code>
   */
  long getSessionId();
}
