// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: recom_rpc.proto

package recommender_rpc;

public interface ParameterOrBuilder extends
    // @@protoc_insertion_point(interface_extends:recommender_rpc.Parameter)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 variableId = 1;</code>
   */
  long getVariableId();

  /**
   * <code>string name = 2;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string type = 3;</code>
   */
  java.lang.String getType();
  /**
   * <code>string type = 3;</code>
   */
  com.google.protobuf.ByteString
      getTypeBytes();

  /**
   * <pre>
   * how to encode? serialized as string?
   * </pre>
   *
   * <code>string value = 10;</code>
   */
  java.lang.String getValue();
  /**
   * <pre>
   * how to encode? serialized as string?
   * </pre>
   *
   * <code>string value = 10;</code>
   */
  com.google.protobuf.ByteString
      getValueBytes();
}
