// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: recom_rpc.proto

package recommender_rpc;

public final class RecommenderRpcProto {
  private RecommenderRpcProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_recommender_rpc_InitialisationReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_recommender_rpc_InitialisationReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_recommender_rpc_InitialisationResp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_recommender_rpc_InitialisationResp_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_recommender_rpc_DisposeRecommenderReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_recommender_rpc_DisposeRecommenderReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_recommender_rpc_DisposeRecommenderResp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_recommender_rpc_DisposeRecommenderResp_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_recommender_rpc_Parameter_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_recommender_rpc_Parameter_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_recommender_rpc_ViewerSelectionState_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_recommender_rpc_ViewerSelectionState_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_recommender_rpc_OnNewInputReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_recommender_rpc_OnNewInputReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_recommender_rpc_SuggesionData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_recommender_rpc_SuggesionData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_recommender_rpc_SuggestionsSetResp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_recommender_rpc_SuggestionsSetResp_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_recommender_rpc_OnSuggestionSelectedReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_recommender_rpc_OnSuggestionSelectedReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_recommender_rpc_SuggestionDetailsResp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_recommender_rpc_SuggestionDetailsResp_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017recom_rpc.proto\022\017recommender_rpc\"\205\001\n\021I" +
      "nitialisationReq\022\025\n\rsettings_path\030\001 \001(\t\022" +
      "\025\n\rprog_language\030\002 \001(\t\022\025\n\rsrc_file_path\030" +
      "\003 \001(\t\022\024\n\014src_dir_path\030\004 \001(\t\022\025\n\rdomain_la" +
      "bels\030\005 \003(\t\"7\n\022InitialisationResp\022\021\n\tsess" +
      "ionId\030\001 \001(\003\022\016\n\006status\030\002 \001(\t\"=\n\025DisposeRe" +
      "commenderReq\022\021\n\tsessionId\030\001 \001(\003\022\021\n\tsaveS" +
      "tate\030\002 \001(\010\";\n\026DisposeRecommenderResp\022\021\n\t" +
      "sessionId\030\001 \001(\003\022\016\n\006status\030\002 \001(\t\"J\n\tParam" +
      "eter\022\022\n\nvariableId\030\001 \001(\003\022\014\n\004name\030\002 \001(\t\022\014" +
      "\n\004type\030\003 \001(\t\022\r\n\005value\030\n \001(\t\"\270\001\n\024ViewerSe" +
      "lectionState\022\024\n\014anySelection\030\001 \001(\010\022\027\n\017va" +
      "riableIdShown\030\002 \001(\003\022\020\n\010rowStart\030\003 \001(\005\022\016\n" +
      "\006rowEnd\030\004 \001(\005\022\024\n\014completeRows\030\005 \001(\010\022\020\n\010c" +
      "olStart\030\n \001(\005\022\016\n\006colEnd\030\013 \001(\005\022\027\n\017complet" +
      "eColumns\030\014 \001(\010\"\261\002\n\rOnNewInputReq\022\021\n\tsess" +
      "ionId\030\001 \001(\003\022\022\n\nsearchText\030\002 \001(\t\022=\n\nchang" +
      "eType\030\003 \001(\0162).recommender_rpc.OnNewInput" +
      "Req.ChangeType\0223\n\017activeVariables\030\n \003(\0132" +
      "\032.recommender_rpc.Parameter\022:\n\013viewerSta" +
      "te\030\024 \001(\0132%.recommender_rpc.ViewerSelecti" +
      "onState\"I\n\nChangeType\022\016\n\nSEARCHTEXT\020\000\022\017\n" +
      "\013VIEWERSTATE\020\001\022\017\n\013PREFERENCES\020\002\022\t\n\005OTHER" +
      "\020\n\"|\n\rSuggesionData\022\024\n\014suggestionID\030\001 \001(" +
      "\003\022\025\n\rsuggestedCode\030\002 \001(\t\022\017\n\007comment\030\005 \001(" +
      "\t\022-\n\tparameter\030\n \003(\0132\032.recommender_rpc.P" +
      "arameter\"\\\n\022SuggestionsSetResp\022\021\n\tsessio" +
      "nId\030\001 \001(\003\0223\n\013suggestions\030\002 \003(\0132\036.recomme" +
      "nder_rpc.SuggesionData\",\n\027OnSuggestionSe" +
      "lectedReq\022\021\n\tsessionId\030\001 \001(\003\"*\n\025Suggesti" +
      "onDetailsResp\022\021\n\tsessionId\030\001 \001(\0032\221\003\n\022Rec" +
      "ommenderService\022X\n\013InitSession\022\".recomme" +
      "nder_rpc.InitialisationReq\032#.recommender" +
      "_rpc.InitialisationResp\"\000\022a\n\014CloseSessio" +
      "n\022&.recommender_rpc.DisposeRecommenderRe" +
      "q\032\'.recommender_rpc.DisposeRecommenderRe" +
      "sp\"\000\022T\n\013onUserInput\022\036.recommender_rpc.On" +
      "NewInputReq\032#.recommender_rpc.Suggestion" +
      "sSetResp\"\000\022h\n\022suggestionSelected\022(.recom" +
      "mender_rpc.OnSuggestionSelectedReq\032&.rec" +
      "ommender_rpc.SuggestionDetailsResp\"\000B3\n\017" +
      "recommender_rpcB\023RecommenderRpcProtoP\001\242\002" +
      "\010RcmdrRPCb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_recommender_rpc_InitialisationReq_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_recommender_rpc_InitialisationReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_recommender_rpc_InitialisationReq_descriptor,
        new java.lang.String[] { "SettingsPath", "ProgLanguage", "SrcFilePath", "SrcDirPath", "DomainLabels", });
    internal_static_recommender_rpc_InitialisationResp_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_recommender_rpc_InitialisationResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_recommender_rpc_InitialisationResp_descriptor,
        new java.lang.String[] { "SessionId", "Status", });
    internal_static_recommender_rpc_DisposeRecommenderReq_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_recommender_rpc_DisposeRecommenderReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_recommender_rpc_DisposeRecommenderReq_descriptor,
        new java.lang.String[] { "SessionId", "SaveState", });
    internal_static_recommender_rpc_DisposeRecommenderResp_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_recommender_rpc_DisposeRecommenderResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_recommender_rpc_DisposeRecommenderResp_descriptor,
        new java.lang.String[] { "SessionId", "Status", });
    internal_static_recommender_rpc_Parameter_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_recommender_rpc_Parameter_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_recommender_rpc_Parameter_descriptor,
        new java.lang.String[] { "VariableId", "Name", "Type", "Value", });
    internal_static_recommender_rpc_ViewerSelectionState_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_recommender_rpc_ViewerSelectionState_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_recommender_rpc_ViewerSelectionState_descriptor,
        new java.lang.String[] { "AnySelection", "VariableIdShown", "RowStart", "RowEnd", "CompleteRows", "ColStart", "ColEnd", "CompleteColumns", });
    internal_static_recommender_rpc_OnNewInputReq_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_recommender_rpc_OnNewInputReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_recommender_rpc_OnNewInputReq_descriptor,
        new java.lang.String[] { "SessionId", "SearchText", "ChangeType", "ActiveVariables", "ViewerState", });
    internal_static_recommender_rpc_SuggesionData_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_recommender_rpc_SuggesionData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_recommender_rpc_SuggesionData_descriptor,
        new java.lang.String[] { "SuggestionID", "SuggestedCode", "Comment", "Parameter", });
    internal_static_recommender_rpc_SuggestionsSetResp_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_recommender_rpc_SuggestionsSetResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_recommender_rpc_SuggestionsSetResp_descriptor,
        new java.lang.String[] { "SessionId", "Suggestions", });
    internal_static_recommender_rpc_OnSuggestionSelectedReq_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_recommender_rpc_OnSuggestionSelectedReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_recommender_rpc_OnSuggestionSelectedReq_descriptor,
        new java.lang.String[] { "SessionId", });
    internal_static_recommender_rpc_SuggestionDetailsResp_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_recommender_rpc_SuggestionDetailsResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_recommender_rpc_SuggestionDetailsResp_descriptor,
        new java.lang.String[] { "SessionId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
