// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: recom_rpc.proto

package recommender_rpc;

/**
 * Protobuf type {@code recommender_rpc.SuggesionData}
 */
public  final class SuggesionData extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:recommender_rpc.SuggesionData)
    SuggesionDataOrBuilder {
private static final long serialVersionUID = 0L;
  // Use SuggesionData.newBuilder() to construct.
  private SuggesionData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SuggesionData() {
    suggestionID_ = 0L;
    suggestedCode_ = "";
    comment_ = "";
    parameter_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private SuggesionData(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            suggestionID_ = input.readInt64();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            suggestedCode_ = s;
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            comment_ = s;
            break;
          }
          case 82: {
            if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
              parameter_ = new java.util.ArrayList<recommender_rpc.Parameter>();
              mutable_bitField0_ |= 0x00000008;
            }
            parameter_.add(
                input.readMessage(recommender_rpc.Parameter.parser(), extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
        parameter_ = java.util.Collections.unmodifiableList(parameter_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return recommender_rpc.RecommenderRpcProto.internal_static_recommender_rpc_SuggesionData_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return recommender_rpc.RecommenderRpcProto.internal_static_recommender_rpc_SuggesionData_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            recommender_rpc.SuggesionData.class, recommender_rpc.SuggesionData.Builder.class);
  }

  private int bitField0_;
  public static final int SUGGESTIONID_FIELD_NUMBER = 1;
  private long suggestionID_;
  /**
   * <code>int64 suggestionID = 1;</code>
   */
  public long getSuggestionID() {
    return suggestionID_;
  }

  public static final int SUGGESTEDCODE_FIELD_NUMBER = 2;
  private volatile java.lang.Object suggestedCode_;
  /**
   * <code>string suggestedCode = 2;</code>
   */
  public java.lang.String getSuggestedCode() {
    java.lang.Object ref = suggestedCode_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      suggestedCode_ = s;
      return s;
    }
  }
  /**
   * <code>string suggestedCode = 2;</code>
   */
  public com.google.protobuf.ByteString
      getSuggestedCodeBytes() {
    java.lang.Object ref = suggestedCode_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      suggestedCode_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int COMMENT_FIELD_NUMBER = 5;
  private volatile java.lang.Object comment_;
  /**
   * <code>string comment = 5;</code>
   */
  public java.lang.String getComment() {
    java.lang.Object ref = comment_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      comment_ = s;
      return s;
    }
  }
  /**
   * <code>string comment = 5;</code>
   */
  public com.google.protobuf.ByteString
      getCommentBytes() {
    java.lang.Object ref = comment_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      comment_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PARAMETER_FIELD_NUMBER = 10;
  private java.util.List<recommender_rpc.Parameter> parameter_;
  /**
   * <pre>
   * todo: later we might use a list of values per placeholder
   * </pre>
   *
   * <code>repeated .recommender_rpc.Parameter parameter = 10;</code>
   */
  public java.util.List<recommender_rpc.Parameter> getParameterList() {
    return parameter_;
  }
  /**
   * <pre>
   * todo: later we might use a list of values per placeholder
   * </pre>
   *
   * <code>repeated .recommender_rpc.Parameter parameter = 10;</code>
   */
  public java.util.List<? extends recommender_rpc.ParameterOrBuilder> 
      getParameterOrBuilderList() {
    return parameter_;
  }
  /**
   * <pre>
   * todo: later we might use a list of values per placeholder
   * </pre>
   *
   * <code>repeated .recommender_rpc.Parameter parameter = 10;</code>
   */
  public int getParameterCount() {
    return parameter_.size();
  }
  /**
   * <pre>
   * todo: later we might use a list of values per placeholder
   * </pre>
   *
   * <code>repeated .recommender_rpc.Parameter parameter = 10;</code>
   */
  public recommender_rpc.Parameter getParameter(int index) {
    return parameter_.get(index);
  }
  /**
   * <pre>
   * todo: later we might use a list of values per placeholder
   * </pre>
   *
   * <code>repeated .recommender_rpc.Parameter parameter = 10;</code>
   */
  public recommender_rpc.ParameterOrBuilder getParameterOrBuilder(
      int index) {
    return parameter_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (suggestionID_ != 0L) {
      output.writeInt64(1, suggestionID_);
    }
    if (!getSuggestedCodeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, suggestedCode_);
    }
    if (!getCommentBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, comment_);
    }
    for (int i = 0; i < parameter_.size(); i++) {
      output.writeMessage(10, parameter_.get(i));
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (suggestionID_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, suggestionID_);
    }
    if (!getSuggestedCodeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, suggestedCode_);
    }
    if (!getCommentBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, comment_);
    }
    for (int i = 0; i < parameter_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(10, parameter_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof recommender_rpc.SuggesionData)) {
      return super.equals(obj);
    }
    recommender_rpc.SuggesionData other = (recommender_rpc.SuggesionData) obj;

    boolean result = true;
    result = result && (getSuggestionID()
        == other.getSuggestionID());
    result = result && getSuggestedCode()
        .equals(other.getSuggestedCode());
    result = result && getComment()
        .equals(other.getComment());
    result = result && getParameterList()
        .equals(other.getParameterList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SUGGESTIONID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getSuggestionID());
    hash = (37 * hash) + SUGGESTEDCODE_FIELD_NUMBER;
    hash = (53 * hash) + getSuggestedCode().hashCode();
    hash = (37 * hash) + COMMENT_FIELD_NUMBER;
    hash = (53 * hash) + getComment().hashCode();
    if (getParameterCount() > 0) {
      hash = (37 * hash) + PARAMETER_FIELD_NUMBER;
      hash = (53 * hash) + getParameterList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static recommender_rpc.SuggesionData parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static recommender_rpc.SuggesionData parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static recommender_rpc.SuggesionData parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static recommender_rpc.SuggesionData parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static recommender_rpc.SuggesionData parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static recommender_rpc.SuggesionData parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static recommender_rpc.SuggesionData parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static recommender_rpc.SuggesionData parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static recommender_rpc.SuggesionData parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static recommender_rpc.SuggesionData parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static recommender_rpc.SuggesionData parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static recommender_rpc.SuggesionData parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(recommender_rpc.SuggesionData prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code recommender_rpc.SuggesionData}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:recommender_rpc.SuggesionData)
      recommender_rpc.SuggesionDataOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return recommender_rpc.RecommenderRpcProto.internal_static_recommender_rpc_SuggesionData_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return recommender_rpc.RecommenderRpcProto.internal_static_recommender_rpc_SuggesionData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              recommender_rpc.SuggesionData.class, recommender_rpc.SuggesionData.Builder.class);
    }

    // Construct using recommender_rpc.SuggesionData.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getParameterFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      suggestionID_ = 0L;

      suggestedCode_ = "";

      comment_ = "";

      if (parameterBuilder_ == null) {
        parameter_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
      } else {
        parameterBuilder_.clear();
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return recommender_rpc.RecommenderRpcProto.internal_static_recommender_rpc_SuggesionData_descriptor;
    }

    public recommender_rpc.SuggesionData getDefaultInstanceForType() {
      return recommender_rpc.SuggesionData.getDefaultInstance();
    }

    public recommender_rpc.SuggesionData build() {
      recommender_rpc.SuggesionData result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public recommender_rpc.SuggesionData buildPartial() {
      recommender_rpc.SuggesionData result = new recommender_rpc.SuggesionData(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.suggestionID_ = suggestionID_;
      result.suggestedCode_ = suggestedCode_;
      result.comment_ = comment_;
      if (parameterBuilder_ == null) {
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          parameter_ = java.util.Collections.unmodifiableList(parameter_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.parameter_ = parameter_;
      } else {
        result.parameter_ = parameterBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof recommender_rpc.SuggesionData) {
        return mergeFrom((recommender_rpc.SuggesionData)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(recommender_rpc.SuggesionData other) {
      if (other == recommender_rpc.SuggesionData.getDefaultInstance()) return this;
      if (other.getSuggestionID() != 0L) {
        setSuggestionID(other.getSuggestionID());
      }
      if (!other.getSuggestedCode().isEmpty()) {
        suggestedCode_ = other.suggestedCode_;
        onChanged();
      }
      if (!other.getComment().isEmpty()) {
        comment_ = other.comment_;
        onChanged();
      }
      if (parameterBuilder_ == null) {
        if (!other.parameter_.isEmpty()) {
          if (parameter_.isEmpty()) {
            parameter_ = other.parameter_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureParameterIsMutable();
            parameter_.addAll(other.parameter_);
          }
          onChanged();
        }
      } else {
        if (!other.parameter_.isEmpty()) {
          if (parameterBuilder_.isEmpty()) {
            parameterBuilder_.dispose();
            parameterBuilder_ = null;
            parameter_ = other.parameter_;
            bitField0_ = (bitField0_ & ~0x00000008);
            parameterBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getParameterFieldBuilder() : null;
          } else {
            parameterBuilder_.addAllMessages(other.parameter_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      recommender_rpc.SuggesionData parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (recommender_rpc.SuggesionData) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private long suggestionID_ ;
    /**
     * <code>int64 suggestionID = 1;</code>
     */
    public long getSuggestionID() {
      return suggestionID_;
    }
    /**
     * <code>int64 suggestionID = 1;</code>
     */
    public Builder setSuggestionID(long value) {
      
      suggestionID_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 suggestionID = 1;</code>
     */
    public Builder clearSuggestionID() {
      
      suggestionID_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object suggestedCode_ = "";
    /**
     * <code>string suggestedCode = 2;</code>
     */
    public java.lang.String getSuggestedCode() {
      java.lang.Object ref = suggestedCode_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        suggestedCode_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string suggestedCode = 2;</code>
     */
    public com.google.protobuf.ByteString
        getSuggestedCodeBytes() {
      java.lang.Object ref = suggestedCode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        suggestedCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string suggestedCode = 2;</code>
     */
    public Builder setSuggestedCode(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      suggestedCode_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string suggestedCode = 2;</code>
     */
    public Builder clearSuggestedCode() {
      
      suggestedCode_ = getDefaultInstance().getSuggestedCode();
      onChanged();
      return this;
    }
    /**
     * <code>string suggestedCode = 2;</code>
     */
    public Builder setSuggestedCodeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      suggestedCode_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object comment_ = "";
    /**
     * <code>string comment = 5;</code>
     */
    public java.lang.String getComment() {
      java.lang.Object ref = comment_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        comment_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string comment = 5;</code>
     */
    public com.google.protobuf.ByteString
        getCommentBytes() {
      java.lang.Object ref = comment_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        comment_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string comment = 5;</code>
     */
    public Builder setComment(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      comment_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string comment = 5;</code>
     */
    public Builder clearComment() {
      
      comment_ = getDefaultInstance().getComment();
      onChanged();
      return this;
    }
    /**
     * <code>string comment = 5;</code>
     */
    public Builder setCommentBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      comment_ = value;
      onChanged();
      return this;
    }

    private java.util.List<recommender_rpc.Parameter> parameter_ =
      java.util.Collections.emptyList();
    private void ensureParameterIsMutable() {
      if (!((bitField0_ & 0x00000008) == 0x00000008)) {
        parameter_ = new java.util.ArrayList<recommender_rpc.Parameter>(parameter_);
        bitField0_ |= 0x00000008;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        recommender_rpc.Parameter, recommender_rpc.Parameter.Builder, recommender_rpc.ParameterOrBuilder> parameterBuilder_;

    /**
     * <pre>
     * todo: later we might use a list of values per placeholder
     * </pre>
     *
     * <code>repeated .recommender_rpc.Parameter parameter = 10;</code>
     */
    public java.util.List<recommender_rpc.Parameter> getParameterList() {
      if (parameterBuilder_ == null) {
        return java.util.Collections.unmodifiableList(parameter_);
      } else {
        return parameterBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * todo: later we might use a list of values per placeholder
     * </pre>
     *
     * <code>repeated .recommender_rpc.Parameter parameter = 10;</code>
     */
    public int getParameterCount() {
      if (parameterBuilder_ == null) {
        return parameter_.size();
      } else {
        return parameterBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * todo: later we might use a list of values per placeholder
     * </pre>
     *
     * <code>repeated .recommender_rpc.Parameter parameter = 10;</code>
     */
    public recommender_rpc.Parameter getParameter(int index) {
      if (parameterBuilder_ == null) {
        return parameter_.get(index);
      } else {
        return parameterBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * todo: later we might use a list of values per placeholder
     * </pre>
     *
     * <code>repeated .recommender_rpc.Parameter parameter = 10;</code>
     */
    public Builder setParameter(
        int index, recommender_rpc.Parameter value) {
      if (parameterBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureParameterIsMutable();
        parameter_.set(index, value);
        onChanged();
      } else {
        parameterBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * todo: later we might use a list of values per placeholder
     * </pre>
     *
     * <code>repeated .recommender_rpc.Parameter parameter = 10;</code>
     */
    public Builder setParameter(
        int index, recommender_rpc.Parameter.Builder builderForValue) {
      if (parameterBuilder_ == null) {
        ensureParameterIsMutable();
        parameter_.set(index, builderForValue.build());
        onChanged();
      } else {
        parameterBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * todo: later we might use a list of values per placeholder
     * </pre>
     *
     * <code>repeated .recommender_rpc.Parameter parameter = 10;</code>
     */
    public Builder addParameter(recommender_rpc.Parameter value) {
      if (parameterBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureParameterIsMutable();
        parameter_.add(value);
        onChanged();
      } else {
        parameterBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * todo: later we might use a list of values per placeholder
     * </pre>
     *
     * <code>repeated .recommender_rpc.Parameter parameter = 10;</code>
     */
    public Builder addParameter(
        int index, recommender_rpc.Parameter value) {
      if (parameterBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureParameterIsMutable();
        parameter_.add(index, value);
        onChanged();
      } else {
        parameterBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * todo: later we might use a list of values per placeholder
     * </pre>
     *
     * <code>repeated .recommender_rpc.Parameter parameter = 10;</code>
     */
    public Builder addParameter(
        recommender_rpc.Parameter.Builder builderForValue) {
      if (parameterBuilder_ == null) {
        ensureParameterIsMutable();
        parameter_.add(builderForValue.build());
        onChanged();
      } else {
        parameterBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * todo: later we might use a list of values per placeholder
     * </pre>
     *
     * <code>repeated .recommender_rpc.Parameter parameter = 10;</code>
     */
    public Builder addParameter(
        int index, recommender_rpc.Parameter.Builder builderForValue) {
      if (parameterBuilder_ == null) {
        ensureParameterIsMutable();
        parameter_.add(index, builderForValue.build());
        onChanged();
      } else {
        parameterBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * todo: later we might use a list of values per placeholder
     * </pre>
     *
     * <code>repeated .recommender_rpc.Parameter parameter = 10;</code>
     */
    public Builder addAllParameter(
        java.lang.Iterable<? extends recommender_rpc.Parameter> values) {
      if (parameterBuilder_ == null) {
        ensureParameterIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, parameter_);
        onChanged();
      } else {
        parameterBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * todo: later we might use a list of values per placeholder
     * </pre>
     *
     * <code>repeated .recommender_rpc.Parameter parameter = 10;</code>
     */
    public Builder clearParameter() {
      if (parameterBuilder_ == null) {
        parameter_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
      } else {
        parameterBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * todo: later we might use a list of values per placeholder
     * </pre>
     *
     * <code>repeated .recommender_rpc.Parameter parameter = 10;</code>
     */
    public Builder removeParameter(int index) {
      if (parameterBuilder_ == null) {
        ensureParameterIsMutable();
        parameter_.remove(index);
        onChanged();
      } else {
        parameterBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * todo: later we might use a list of values per placeholder
     * </pre>
     *
     * <code>repeated .recommender_rpc.Parameter parameter = 10;</code>
     */
    public recommender_rpc.Parameter.Builder getParameterBuilder(
        int index) {
      return getParameterFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * todo: later we might use a list of values per placeholder
     * </pre>
     *
     * <code>repeated .recommender_rpc.Parameter parameter = 10;</code>
     */
    public recommender_rpc.ParameterOrBuilder getParameterOrBuilder(
        int index) {
      if (parameterBuilder_ == null) {
        return parameter_.get(index);  } else {
        return parameterBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * todo: later we might use a list of values per placeholder
     * </pre>
     *
     * <code>repeated .recommender_rpc.Parameter parameter = 10;</code>
     */
    public java.util.List<? extends recommender_rpc.ParameterOrBuilder> 
         getParameterOrBuilderList() {
      if (parameterBuilder_ != null) {
        return parameterBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(parameter_);
      }
    }
    /**
     * <pre>
     * todo: later we might use a list of values per placeholder
     * </pre>
     *
     * <code>repeated .recommender_rpc.Parameter parameter = 10;</code>
     */
    public recommender_rpc.Parameter.Builder addParameterBuilder() {
      return getParameterFieldBuilder().addBuilder(
          recommender_rpc.Parameter.getDefaultInstance());
    }
    /**
     * <pre>
     * todo: later we might use a list of values per placeholder
     * </pre>
     *
     * <code>repeated .recommender_rpc.Parameter parameter = 10;</code>
     */
    public recommender_rpc.Parameter.Builder addParameterBuilder(
        int index) {
      return getParameterFieldBuilder().addBuilder(
          index, recommender_rpc.Parameter.getDefaultInstance());
    }
    /**
     * <pre>
     * todo: later we might use a list of values per placeholder
     * </pre>
     *
     * <code>repeated .recommender_rpc.Parameter parameter = 10;</code>
     */
    public java.util.List<recommender_rpc.Parameter.Builder> 
         getParameterBuilderList() {
      return getParameterFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        recommender_rpc.Parameter, recommender_rpc.Parameter.Builder, recommender_rpc.ParameterOrBuilder> 
        getParameterFieldBuilder() {
      if (parameterBuilder_ == null) {
        parameterBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            recommender_rpc.Parameter, recommender_rpc.Parameter.Builder, recommender_rpc.ParameterOrBuilder>(
                parameter_,
                ((bitField0_ & 0x00000008) == 0x00000008),
                getParentForChildren(),
                isClean());
        parameter_ = null;
      }
      return parameterBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:recommender_rpc.SuggesionData)
  }

  // @@protoc_insertion_point(class_scope:recommender_rpc.SuggesionData)
  private static final recommender_rpc.SuggesionData DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new recommender_rpc.SuggesionData();
  }

  public static recommender_rpc.SuggesionData getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SuggesionData>
      PARSER = new com.google.protobuf.AbstractParser<SuggesionData>() {
    public SuggesionData parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new SuggesionData(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<SuggesionData> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SuggesionData> getParserForType() {
    return PARSER;
  }

  public recommender_rpc.SuggesionData getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

