// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: recom_rpc.proto

package recommender_rpc;

public interface SuggestionsSetRespOrBuilder extends
    // @@protoc_insertion_point(interface_extends:recommender_rpc.SuggestionsSetResp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 sessionId = 1;</code>
   */
  long getSessionId();

  /**
   * <pre>
   * change of this response compared to previous one
   * </pre>
   *
   * <code>.recommender_rpc.SuggestionsSetResp.ResponseChange responseChange = 2;</code>
   */
  int getResponseChangeValue();
  /**
   * <pre>
   * change of this response compared to previous one
   * </pre>
   *
   * <code>.recommender_rpc.SuggestionsSetResp.ResponseChange responseChange = 2;</code>
   */
  recommender_rpc.SuggestionsSetResp.ResponseChange getResponseChange();

  /**
   * <code>repeated .recommender_rpc.SuggesionItem suggestionItems = 3;</code>
   */
  java.util.List<recommender_rpc.SuggesionItem> 
      getSuggestionItemsList();
  /**
   * <code>repeated .recommender_rpc.SuggesionItem suggestionItems = 3;</code>
   */
  recommender_rpc.SuggesionItem getSuggestionItems(int index);
  /**
   * <code>repeated .recommender_rpc.SuggesionItem suggestionItems = 3;</code>
   */
  int getSuggestionItemsCount();
  /**
   * <code>repeated .recommender_rpc.SuggesionItem suggestionItems = 3;</code>
   */
  java.util.List<? extends recommender_rpc.SuggesionItemOrBuilder> 
      getSuggestionItemsOrBuilderList();
  /**
   * <code>repeated .recommender_rpc.SuggesionItem suggestionItems = 3;</code>
   */
  recommender_rpc.SuggesionItemOrBuilder getSuggestionItemsOrBuilder(
      int index);
}
