// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: recom_rpc.proto

package recommender_rpc;

/**
 * <pre>
 * The list of suggestions, main answer from the recom-engine
 * </pre>
 *
 * Protobuf type {@code recommender_rpc.SuggestionsSetResp}
 */
public  final class SuggestionsSetResp extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:recommender_rpc.SuggestionsSetResp)
    SuggestionsSetRespOrBuilder {
private static final long serialVersionUID = 0L;
  // Use SuggestionsSetResp.newBuilder() to construct.
  private SuggestionsSetResp(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SuggestionsSetResp() {
    sessionId_ = 0L;
    responseChange_ = 0;
    suggestionItems_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private SuggestionsSetResp(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            sessionId_ = input.readInt64();
            break;
          }
          case 16: {
            int rawValue = input.readEnum();

            responseChange_ = rawValue;
            break;
          }
          case 26: {
            if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
              suggestionItems_ = new java.util.ArrayList<recommender_rpc.SuggesionItem>();
              mutable_bitField0_ |= 0x00000004;
            }
            suggestionItems_.add(
                input.readMessage(recommender_rpc.SuggesionItem.parser(), extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
        suggestionItems_ = java.util.Collections.unmodifiableList(suggestionItems_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return recommender_rpc.RecommenderRpcProto.internal_static_recommender_rpc_SuggestionsSetResp_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return recommender_rpc.RecommenderRpcProto.internal_static_recommender_rpc_SuggestionsSetResp_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            recommender_rpc.SuggestionsSetResp.class, recommender_rpc.SuggestionsSetResp.Builder.class);
  }

  /**
   * Protobuf enum {@code recommender_rpc.SuggestionsSetResp.ResponseChange}
   */
  public enum ResponseChange
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>NO_CHANGE = 0;</code>
     */
    NO_CHANGE(0),
    /**
     * <code>UPDATE = 1;</code>
     */
    UPDATE(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>NO_CHANGE = 0;</code>
     */
    public static final int NO_CHANGE_VALUE = 0;
    /**
     * <code>UPDATE = 1;</code>
     */
    public static final int UPDATE_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ResponseChange valueOf(int value) {
      return forNumber(value);
    }

    public static ResponseChange forNumber(int value) {
      switch (value) {
        case 0: return NO_CHANGE;
        case 1: return UPDATE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ResponseChange>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ResponseChange> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ResponseChange>() {
            public ResponseChange findValueByNumber(int number) {
              return ResponseChange.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return recommender_rpc.SuggestionsSetResp.getDescriptor().getEnumTypes().get(0);
    }

    private static final ResponseChange[] VALUES = values();

    public static ResponseChange valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private ResponseChange(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:recommender_rpc.SuggestionsSetResp.ResponseChange)
  }

  private int bitField0_;
  public static final int SESSIONID_FIELD_NUMBER = 1;
  private long sessionId_;
  /**
   * <code>int64 sessionId = 1;</code>
   */
  public long getSessionId() {
    return sessionId_;
  }

  public static final int RESPONSECHANGE_FIELD_NUMBER = 2;
  private int responseChange_;
  /**
   * <pre>
   * change of this response compared to previous one
   * </pre>
   *
   * <code>.recommender_rpc.SuggestionsSetResp.ResponseChange responseChange = 2;</code>
   */
  public int getResponseChangeValue() {
    return responseChange_;
  }
  /**
   * <pre>
   * change of this response compared to previous one
   * </pre>
   *
   * <code>.recommender_rpc.SuggestionsSetResp.ResponseChange responseChange = 2;</code>
   */
  public recommender_rpc.SuggestionsSetResp.ResponseChange getResponseChange() {
    recommender_rpc.SuggestionsSetResp.ResponseChange result = recommender_rpc.SuggestionsSetResp.ResponseChange.valueOf(responseChange_);
    return result == null ? recommender_rpc.SuggestionsSetResp.ResponseChange.UNRECOGNIZED : result;
  }

  public static final int SUGGESTIONITEMS_FIELD_NUMBER = 3;
  private java.util.List<recommender_rpc.SuggesionItem> suggestionItems_;
  /**
   * <code>repeated .recommender_rpc.SuggesionItem suggestionItems = 3;</code>
   */
  public java.util.List<recommender_rpc.SuggesionItem> getSuggestionItemsList() {
    return suggestionItems_;
  }
  /**
   * <code>repeated .recommender_rpc.SuggesionItem suggestionItems = 3;</code>
   */
  public java.util.List<? extends recommender_rpc.SuggesionItemOrBuilder> 
      getSuggestionItemsOrBuilderList() {
    return suggestionItems_;
  }
  /**
   * <code>repeated .recommender_rpc.SuggesionItem suggestionItems = 3;</code>
   */
  public int getSuggestionItemsCount() {
    return suggestionItems_.size();
  }
  /**
   * <code>repeated .recommender_rpc.SuggesionItem suggestionItems = 3;</code>
   */
  public recommender_rpc.SuggesionItem getSuggestionItems(int index) {
    return suggestionItems_.get(index);
  }
  /**
   * <code>repeated .recommender_rpc.SuggesionItem suggestionItems = 3;</code>
   */
  public recommender_rpc.SuggesionItemOrBuilder getSuggestionItemsOrBuilder(
      int index) {
    return suggestionItems_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (sessionId_ != 0L) {
      output.writeInt64(1, sessionId_);
    }
    if (responseChange_ != recommender_rpc.SuggestionsSetResp.ResponseChange.NO_CHANGE.getNumber()) {
      output.writeEnum(2, responseChange_);
    }
    for (int i = 0; i < suggestionItems_.size(); i++) {
      output.writeMessage(3, suggestionItems_.get(i));
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (sessionId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, sessionId_);
    }
    if (responseChange_ != recommender_rpc.SuggestionsSetResp.ResponseChange.NO_CHANGE.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(2, responseChange_);
    }
    for (int i = 0; i < suggestionItems_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, suggestionItems_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof recommender_rpc.SuggestionsSetResp)) {
      return super.equals(obj);
    }
    recommender_rpc.SuggestionsSetResp other = (recommender_rpc.SuggestionsSetResp) obj;

    boolean result = true;
    result = result && (getSessionId()
        == other.getSessionId());
    result = result && responseChange_ == other.responseChange_;
    result = result && getSuggestionItemsList()
        .equals(other.getSuggestionItemsList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SESSIONID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getSessionId());
    hash = (37 * hash) + RESPONSECHANGE_FIELD_NUMBER;
    hash = (53 * hash) + responseChange_;
    if (getSuggestionItemsCount() > 0) {
      hash = (37 * hash) + SUGGESTIONITEMS_FIELD_NUMBER;
      hash = (53 * hash) + getSuggestionItemsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static recommender_rpc.SuggestionsSetResp parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static recommender_rpc.SuggestionsSetResp parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static recommender_rpc.SuggestionsSetResp parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static recommender_rpc.SuggestionsSetResp parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static recommender_rpc.SuggestionsSetResp parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static recommender_rpc.SuggestionsSetResp parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static recommender_rpc.SuggestionsSetResp parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static recommender_rpc.SuggestionsSetResp parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static recommender_rpc.SuggestionsSetResp parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static recommender_rpc.SuggestionsSetResp parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static recommender_rpc.SuggestionsSetResp parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static recommender_rpc.SuggestionsSetResp parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(recommender_rpc.SuggestionsSetResp prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * The list of suggestions, main answer from the recom-engine
   * </pre>
   *
   * Protobuf type {@code recommender_rpc.SuggestionsSetResp}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:recommender_rpc.SuggestionsSetResp)
      recommender_rpc.SuggestionsSetRespOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return recommender_rpc.RecommenderRpcProto.internal_static_recommender_rpc_SuggestionsSetResp_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return recommender_rpc.RecommenderRpcProto.internal_static_recommender_rpc_SuggestionsSetResp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              recommender_rpc.SuggestionsSetResp.class, recommender_rpc.SuggestionsSetResp.Builder.class);
    }

    // Construct using recommender_rpc.SuggestionsSetResp.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getSuggestionItemsFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      sessionId_ = 0L;

      responseChange_ = 0;

      if (suggestionItemsBuilder_ == null) {
        suggestionItems_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
      } else {
        suggestionItemsBuilder_.clear();
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return recommender_rpc.RecommenderRpcProto.internal_static_recommender_rpc_SuggestionsSetResp_descriptor;
    }

    public recommender_rpc.SuggestionsSetResp getDefaultInstanceForType() {
      return recommender_rpc.SuggestionsSetResp.getDefaultInstance();
    }

    public recommender_rpc.SuggestionsSetResp build() {
      recommender_rpc.SuggestionsSetResp result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public recommender_rpc.SuggestionsSetResp buildPartial() {
      recommender_rpc.SuggestionsSetResp result = new recommender_rpc.SuggestionsSetResp(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.sessionId_ = sessionId_;
      result.responseChange_ = responseChange_;
      if (suggestionItemsBuilder_ == null) {
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          suggestionItems_ = java.util.Collections.unmodifiableList(suggestionItems_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.suggestionItems_ = suggestionItems_;
      } else {
        result.suggestionItems_ = suggestionItemsBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof recommender_rpc.SuggestionsSetResp) {
        return mergeFrom((recommender_rpc.SuggestionsSetResp)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(recommender_rpc.SuggestionsSetResp other) {
      if (other == recommender_rpc.SuggestionsSetResp.getDefaultInstance()) return this;
      if (other.getSessionId() != 0L) {
        setSessionId(other.getSessionId());
      }
      if (other.responseChange_ != 0) {
        setResponseChangeValue(other.getResponseChangeValue());
      }
      if (suggestionItemsBuilder_ == null) {
        if (!other.suggestionItems_.isEmpty()) {
          if (suggestionItems_.isEmpty()) {
            suggestionItems_ = other.suggestionItems_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureSuggestionItemsIsMutable();
            suggestionItems_.addAll(other.suggestionItems_);
          }
          onChanged();
        }
      } else {
        if (!other.suggestionItems_.isEmpty()) {
          if (suggestionItemsBuilder_.isEmpty()) {
            suggestionItemsBuilder_.dispose();
            suggestionItemsBuilder_ = null;
            suggestionItems_ = other.suggestionItems_;
            bitField0_ = (bitField0_ & ~0x00000004);
            suggestionItemsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getSuggestionItemsFieldBuilder() : null;
          } else {
            suggestionItemsBuilder_.addAllMessages(other.suggestionItems_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      recommender_rpc.SuggestionsSetResp parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (recommender_rpc.SuggestionsSetResp) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private long sessionId_ ;
    /**
     * <code>int64 sessionId = 1;</code>
     */
    public long getSessionId() {
      return sessionId_;
    }
    /**
     * <code>int64 sessionId = 1;</code>
     */
    public Builder setSessionId(long value) {
      
      sessionId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 sessionId = 1;</code>
     */
    public Builder clearSessionId() {
      
      sessionId_ = 0L;
      onChanged();
      return this;
    }

    private int responseChange_ = 0;
    /**
     * <pre>
     * change of this response compared to previous one
     * </pre>
     *
     * <code>.recommender_rpc.SuggestionsSetResp.ResponseChange responseChange = 2;</code>
     */
    public int getResponseChangeValue() {
      return responseChange_;
    }
    /**
     * <pre>
     * change of this response compared to previous one
     * </pre>
     *
     * <code>.recommender_rpc.SuggestionsSetResp.ResponseChange responseChange = 2;</code>
     */
    public Builder setResponseChangeValue(int value) {
      responseChange_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * change of this response compared to previous one
     * </pre>
     *
     * <code>.recommender_rpc.SuggestionsSetResp.ResponseChange responseChange = 2;</code>
     */
    public recommender_rpc.SuggestionsSetResp.ResponseChange getResponseChange() {
      recommender_rpc.SuggestionsSetResp.ResponseChange result = recommender_rpc.SuggestionsSetResp.ResponseChange.valueOf(responseChange_);
      return result == null ? recommender_rpc.SuggestionsSetResp.ResponseChange.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * change of this response compared to previous one
     * </pre>
     *
     * <code>.recommender_rpc.SuggestionsSetResp.ResponseChange responseChange = 2;</code>
     */
    public Builder setResponseChange(recommender_rpc.SuggestionsSetResp.ResponseChange value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      responseChange_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * change of this response compared to previous one
     * </pre>
     *
     * <code>.recommender_rpc.SuggestionsSetResp.ResponseChange responseChange = 2;</code>
     */
    public Builder clearResponseChange() {
      
      responseChange_ = 0;
      onChanged();
      return this;
    }

    private java.util.List<recommender_rpc.SuggesionItem> suggestionItems_ =
      java.util.Collections.emptyList();
    private void ensureSuggestionItemsIsMutable() {
      if (!((bitField0_ & 0x00000004) == 0x00000004)) {
        suggestionItems_ = new java.util.ArrayList<recommender_rpc.SuggesionItem>(suggestionItems_);
        bitField0_ |= 0x00000004;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        recommender_rpc.SuggesionItem, recommender_rpc.SuggesionItem.Builder, recommender_rpc.SuggesionItemOrBuilder> suggestionItemsBuilder_;

    /**
     * <code>repeated .recommender_rpc.SuggesionItem suggestionItems = 3;</code>
     */
    public java.util.List<recommender_rpc.SuggesionItem> getSuggestionItemsList() {
      if (suggestionItemsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(suggestionItems_);
      } else {
        return suggestionItemsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .recommender_rpc.SuggesionItem suggestionItems = 3;</code>
     */
    public int getSuggestionItemsCount() {
      if (suggestionItemsBuilder_ == null) {
        return suggestionItems_.size();
      } else {
        return suggestionItemsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .recommender_rpc.SuggesionItem suggestionItems = 3;</code>
     */
    public recommender_rpc.SuggesionItem getSuggestionItems(int index) {
      if (suggestionItemsBuilder_ == null) {
        return suggestionItems_.get(index);
      } else {
        return suggestionItemsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .recommender_rpc.SuggesionItem suggestionItems = 3;</code>
     */
    public Builder setSuggestionItems(
        int index, recommender_rpc.SuggesionItem value) {
      if (suggestionItemsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSuggestionItemsIsMutable();
        suggestionItems_.set(index, value);
        onChanged();
      } else {
        suggestionItemsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .recommender_rpc.SuggesionItem suggestionItems = 3;</code>
     */
    public Builder setSuggestionItems(
        int index, recommender_rpc.SuggesionItem.Builder builderForValue) {
      if (suggestionItemsBuilder_ == null) {
        ensureSuggestionItemsIsMutable();
        suggestionItems_.set(index, builderForValue.build());
        onChanged();
      } else {
        suggestionItemsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .recommender_rpc.SuggesionItem suggestionItems = 3;</code>
     */
    public Builder addSuggestionItems(recommender_rpc.SuggesionItem value) {
      if (suggestionItemsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSuggestionItemsIsMutable();
        suggestionItems_.add(value);
        onChanged();
      } else {
        suggestionItemsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .recommender_rpc.SuggesionItem suggestionItems = 3;</code>
     */
    public Builder addSuggestionItems(
        int index, recommender_rpc.SuggesionItem value) {
      if (suggestionItemsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSuggestionItemsIsMutable();
        suggestionItems_.add(index, value);
        onChanged();
      } else {
        suggestionItemsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .recommender_rpc.SuggesionItem suggestionItems = 3;</code>
     */
    public Builder addSuggestionItems(
        recommender_rpc.SuggesionItem.Builder builderForValue) {
      if (suggestionItemsBuilder_ == null) {
        ensureSuggestionItemsIsMutable();
        suggestionItems_.add(builderForValue.build());
        onChanged();
      } else {
        suggestionItemsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .recommender_rpc.SuggesionItem suggestionItems = 3;</code>
     */
    public Builder addSuggestionItems(
        int index, recommender_rpc.SuggesionItem.Builder builderForValue) {
      if (suggestionItemsBuilder_ == null) {
        ensureSuggestionItemsIsMutable();
        suggestionItems_.add(index, builderForValue.build());
        onChanged();
      } else {
        suggestionItemsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .recommender_rpc.SuggesionItem suggestionItems = 3;</code>
     */
    public Builder addAllSuggestionItems(
        java.lang.Iterable<? extends recommender_rpc.SuggesionItem> values) {
      if (suggestionItemsBuilder_ == null) {
        ensureSuggestionItemsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, suggestionItems_);
        onChanged();
      } else {
        suggestionItemsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .recommender_rpc.SuggesionItem suggestionItems = 3;</code>
     */
    public Builder clearSuggestionItems() {
      if (suggestionItemsBuilder_ == null) {
        suggestionItems_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
      } else {
        suggestionItemsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .recommender_rpc.SuggesionItem suggestionItems = 3;</code>
     */
    public Builder removeSuggestionItems(int index) {
      if (suggestionItemsBuilder_ == null) {
        ensureSuggestionItemsIsMutable();
        suggestionItems_.remove(index);
        onChanged();
      } else {
        suggestionItemsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .recommender_rpc.SuggesionItem suggestionItems = 3;</code>
     */
    public recommender_rpc.SuggesionItem.Builder getSuggestionItemsBuilder(
        int index) {
      return getSuggestionItemsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .recommender_rpc.SuggesionItem suggestionItems = 3;</code>
     */
    public recommender_rpc.SuggesionItemOrBuilder getSuggestionItemsOrBuilder(
        int index) {
      if (suggestionItemsBuilder_ == null) {
        return suggestionItems_.get(index);  } else {
        return suggestionItemsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .recommender_rpc.SuggesionItem suggestionItems = 3;</code>
     */
    public java.util.List<? extends recommender_rpc.SuggesionItemOrBuilder> 
         getSuggestionItemsOrBuilderList() {
      if (suggestionItemsBuilder_ != null) {
        return suggestionItemsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(suggestionItems_);
      }
    }
    /**
     * <code>repeated .recommender_rpc.SuggesionItem suggestionItems = 3;</code>
     */
    public recommender_rpc.SuggesionItem.Builder addSuggestionItemsBuilder() {
      return getSuggestionItemsFieldBuilder().addBuilder(
          recommender_rpc.SuggesionItem.getDefaultInstance());
    }
    /**
     * <code>repeated .recommender_rpc.SuggesionItem suggestionItems = 3;</code>
     */
    public recommender_rpc.SuggesionItem.Builder addSuggestionItemsBuilder(
        int index) {
      return getSuggestionItemsFieldBuilder().addBuilder(
          index, recommender_rpc.SuggesionItem.getDefaultInstance());
    }
    /**
     * <code>repeated .recommender_rpc.SuggesionItem suggestionItems = 3;</code>
     */
    public java.util.List<recommender_rpc.SuggesionItem.Builder> 
         getSuggestionItemsBuilderList() {
      return getSuggestionItemsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        recommender_rpc.SuggesionItem, recommender_rpc.SuggesionItem.Builder, recommender_rpc.SuggesionItemOrBuilder> 
        getSuggestionItemsFieldBuilder() {
      if (suggestionItemsBuilder_ == null) {
        suggestionItemsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            recommender_rpc.SuggesionItem, recommender_rpc.SuggesionItem.Builder, recommender_rpc.SuggesionItemOrBuilder>(
                suggestionItems_,
                ((bitField0_ & 0x00000004) == 0x00000004),
                getParentForChildren(),
                isClean());
        suggestionItems_ = null;
      }
      return suggestionItemsBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:recommender_rpc.SuggestionsSetResp)
  }

  // @@protoc_insertion_point(class_scope:recommender_rpc.SuggestionsSetResp)
  private static final recommender_rpc.SuggestionsSetResp DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new recommender_rpc.SuggestionsSetResp();
  }

  public static recommender_rpc.SuggestionsSetResp getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SuggestionsSetResp>
      PARSER = new com.google.protobuf.AbstractParser<SuggestionsSetResp>() {
    public SuggestionsSetResp parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new SuggestionsSetResp(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<SuggestionsSetResp> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SuggestionsSetResp> getParserForType() {
    return PARSER;
  }

  public recommender_rpc.SuggestionsSetResp getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

