// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: recom_rpc.proto

package recommender_rpc;

public interface SuggesionDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:recommender_rpc.SuggesionData)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 suggestionID = 1;</code>
   */
  long getSuggestionID();

  /**
   * <code>string suggestedCode = 2;</code>
   */
  java.lang.String getSuggestedCode();
  /**
   * <code>string suggestedCode = 2;</code>
   */
  com.google.protobuf.ByteString
      getSuggestedCodeBytes();

  /**
   * <code>string comment = 5;</code>
   */
  java.lang.String getComment();
  /**
   * <code>string comment = 5;</code>
   */
  com.google.protobuf.ByteString
      getCommentBytes();

  /**
   * <pre>
   * todo: later we might use a list of values per placeholder
   * </pre>
   *
   * <code>repeated .recommender_rpc.Parameter parameter = 10;</code>
   */
  java.util.List<recommender_rpc.Parameter> 
      getParameterList();
  /**
   * <pre>
   * todo: later we might use a list of values per placeholder
   * </pre>
   *
   * <code>repeated .recommender_rpc.Parameter parameter = 10;</code>
   */
  recommender_rpc.Parameter getParameter(int index);
  /**
   * <pre>
   * todo: later we might use a list of values per placeholder
   * </pre>
   *
   * <code>repeated .recommender_rpc.Parameter parameter = 10;</code>
   */
  int getParameterCount();
  /**
   * <pre>
   * todo: later we might use a list of values per placeholder
   * </pre>
   *
   * <code>repeated .recommender_rpc.Parameter parameter = 10;</code>
   */
  java.util.List<? extends recommender_rpc.ParameterOrBuilder> 
      getParameterOrBuilderList();
  /**
   * <pre>
   * todo: later we might use a list of values per placeholder
   * </pre>
   *
   * <code>repeated .recommender_rpc.Parameter parameter = 10;</code>
   */
  recommender_rpc.ParameterOrBuilder getParameterOrBuilder(
      int index);
}
