// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: recom_rpc.proto

package recommender_rpc;

public interface UserFocusHintOrBuilder extends
    // @@protoc_insertion_point(interface_extends:recommender_rpc.UserFocusHint)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * name of the variable, domain, keyword
   * </pre>
   *
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <pre>
   * name of the variable, domain, keyword
   * </pre>
   *
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <pre>
   * optional, for some cases obsolete
   * </pre>
   *
   * <code>string value = 2;</code>
   */
  java.lang.String getValue();
  /**
   * <pre>
   * optional, for some cases obsolete
   * </pre>
   *
   * <code>string value = 2;</code>
   */
  com.google.protobuf.ByteString
      getValueBytes();

  /**
   * <code>.recommender_rpc.UserFocusHint.HintType hintType = 3;</code>
   */
  int getHintTypeValue();
  /**
   * <code>.recommender_rpc.UserFocusHint.HintType hintType = 3;</code>
   */
  recommender_rpc.UserFocusHint.HintType getHintType();
}
