// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: recom_rpc.proto

package recommender_rpc;

/**
 * <pre>
 * A focus hint/parameter set by user as na additional info
 * Can be a "preference" for working variables, domains, keywords, other settings ...
 * for later GUI extension
 * </pre>
 *
 * Protobuf type {@code recommender_rpc.UserFocusHint}
 */
public  final class UserFocusHint extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:recommender_rpc.UserFocusHint)
    UserFocusHintOrBuilder {
private static final long serialVersionUID = 0L;
  // Use UserFocusHint.newBuilder() to construct.
  private UserFocusHint(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private UserFocusHint() {
    name_ = "";
    value_ = "";
    hintType_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private UserFocusHint(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            name_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            value_ = s;
            break;
          }
          case 24: {
            int rawValue = input.readEnum();

            hintType_ = rawValue;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return recommender_rpc.RecommenderRpcProto.internal_static_recommender_rpc_UserFocusHint_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return recommender_rpc.RecommenderRpcProto.internal_static_recommender_rpc_UserFocusHint_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            recommender_rpc.UserFocusHint.class, recommender_rpc.UserFocusHint.Builder.class);
  }

  /**
   * Protobuf enum {@code recommender_rpc.UserFocusHint.HintType}
   */
  public enum HintType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>VARIABLE = 0;</code>
     */
    VARIABLE(0),
    /**
     * <code>DOMAIN = 1;</code>
     */
    DOMAIN(1),
    /**
     * <code>KEYWORD = 2;</code>
     */
    KEYWORD(2),
    /**
     * <code>SETTING = 3;</code>
     */
    SETTING(3),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>VARIABLE = 0;</code>
     */
    public static final int VARIABLE_VALUE = 0;
    /**
     * <code>DOMAIN = 1;</code>
     */
    public static final int DOMAIN_VALUE = 1;
    /**
     * <code>KEYWORD = 2;</code>
     */
    public static final int KEYWORD_VALUE = 2;
    /**
     * <code>SETTING = 3;</code>
     */
    public static final int SETTING_VALUE = 3;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static HintType valueOf(int value) {
      return forNumber(value);
    }

    public static HintType forNumber(int value) {
      switch (value) {
        case 0: return VARIABLE;
        case 1: return DOMAIN;
        case 2: return KEYWORD;
        case 3: return SETTING;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<HintType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        HintType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<HintType>() {
            public HintType findValueByNumber(int number) {
              return HintType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return recommender_rpc.UserFocusHint.getDescriptor().getEnumTypes().get(0);
    }

    private static final HintType[] VALUES = values();

    public static HintType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private HintType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:recommender_rpc.UserFocusHint.HintType)
  }

  /**
   * Protobuf enum {@code recommender_rpc.UserFocusHint.HintImpact}
   */
  public enum HintImpact
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     * means: always include this var in suggested fragments
     * </pre>
     *
     * <code>INCLUDE_ALLWAYS = 0;</code>
     */
    INCLUDE_ALLWAYS(0),
    /**
     * <pre>
     * means: prefer this var in suggested fragments
     * </pre>
     *
     * <code>PREFER = 1;</code>
     */
    PREFER(1),
    /**
     * <pre>
     * means: always exclude this var from suggested fragments
     * </pre>
     *
     * <code>EXCLUDE_ALLWAYS = 2;</code>
     */
    EXCLUDE_ALLWAYS(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     * means: always include this var in suggested fragments
     * </pre>
     *
     * <code>INCLUDE_ALLWAYS = 0;</code>
     */
    public static final int INCLUDE_ALLWAYS_VALUE = 0;
    /**
     * <pre>
     * means: prefer this var in suggested fragments
     * </pre>
     *
     * <code>PREFER = 1;</code>
     */
    public static final int PREFER_VALUE = 1;
    /**
     * <pre>
     * means: always exclude this var from suggested fragments
     * </pre>
     *
     * <code>EXCLUDE_ALLWAYS = 2;</code>
     */
    public static final int EXCLUDE_ALLWAYS_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static HintImpact valueOf(int value) {
      return forNumber(value);
    }

    public static HintImpact forNumber(int value) {
      switch (value) {
        case 0: return INCLUDE_ALLWAYS;
        case 1: return PREFER;
        case 2: return EXCLUDE_ALLWAYS;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<HintImpact>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        HintImpact> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<HintImpact>() {
            public HintImpact findValueByNumber(int number) {
              return HintImpact.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return recommender_rpc.UserFocusHint.getDescriptor().getEnumTypes().get(1);
    }

    private static final HintImpact[] VALUES = values();

    public static HintImpact valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private HintImpact(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:recommender_rpc.UserFocusHint.HintImpact)
  }

  public static final int NAME_FIELD_NUMBER = 1;
  private volatile java.lang.Object name_;
  /**
   * <pre>
   * name of the variable, domain, keyword
   * </pre>
   *
   * <code>string name = 1;</code>
   */
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * name of the variable, domain, keyword
   * </pre>
   *
   * <code>string name = 1;</code>
   */
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int VALUE_FIELD_NUMBER = 2;
  private volatile java.lang.Object value_;
  /**
   * <pre>
   * optional, for some cases obsolete
   * </pre>
   *
   * <code>string value = 2;</code>
   */
  public java.lang.String getValue() {
    java.lang.Object ref = value_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      value_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * optional, for some cases obsolete
   * </pre>
   *
   * <code>string value = 2;</code>
   */
  public com.google.protobuf.ByteString
      getValueBytes() {
    java.lang.Object ref = value_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      value_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int HINTTYPE_FIELD_NUMBER = 3;
  private int hintType_;
  /**
   * <code>.recommender_rpc.UserFocusHint.HintType hintType = 3;</code>
   */
  public int getHintTypeValue() {
    return hintType_;
  }
  /**
   * <code>.recommender_rpc.UserFocusHint.HintType hintType = 3;</code>
   */
  public recommender_rpc.UserFocusHint.HintType getHintType() {
    recommender_rpc.UserFocusHint.HintType result = recommender_rpc.UserFocusHint.HintType.valueOf(hintType_);
    return result == null ? recommender_rpc.UserFocusHint.HintType.UNRECOGNIZED : result;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
    }
    if (!getValueBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, value_);
    }
    if (hintType_ != recommender_rpc.UserFocusHint.HintType.VARIABLE.getNumber()) {
      output.writeEnum(3, hintType_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
    }
    if (!getValueBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, value_);
    }
    if (hintType_ != recommender_rpc.UserFocusHint.HintType.VARIABLE.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(3, hintType_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof recommender_rpc.UserFocusHint)) {
      return super.equals(obj);
    }
    recommender_rpc.UserFocusHint other = (recommender_rpc.UserFocusHint) obj;

    boolean result = true;
    result = result && getName()
        .equals(other.getName());
    result = result && getValue()
        .equals(other.getValue());
    result = result && hintType_ == other.hintType_;
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + VALUE_FIELD_NUMBER;
    hash = (53 * hash) + getValue().hashCode();
    hash = (37 * hash) + HINTTYPE_FIELD_NUMBER;
    hash = (53 * hash) + hintType_;
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static recommender_rpc.UserFocusHint parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static recommender_rpc.UserFocusHint parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static recommender_rpc.UserFocusHint parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static recommender_rpc.UserFocusHint parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static recommender_rpc.UserFocusHint parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static recommender_rpc.UserFocusHint parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static recommender_rpc.UserFocusHint parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static recommender_rpc.UserFocusHint parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static recommender_rpc.UserFocusHint parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static recommender_rpc.UserFocusHint parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static recommender_rpc.UserFocusHint parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static recommender_rpc.UserFocusHint parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(recommender_rpc.UserFocusHint prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * A focus hint/parameter set by user as na additional info
   * Can be a "preference" for working variables, domains, keywords, other settings ...
   * for later GUI extension
   * </pre>
   *
   * Protobuf type {@code recommender_rpc.UserFocusHint}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:recommender_rpc.UserFocusHint)
      recommender_rpc.UserFocusHintOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return recommender_rpc.RecommenderRpcProto.internal_static_recommender_rpc_UserFocusHint_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return recommender_rpc.RecommenderRpcProto.internal_static_recommender_rpc_UserFocusHint_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              recommender_rpc.UserFocusHint.class, recommender_rpc.UserFocusHint.Builder.class);
    }

    // Construct using recommender_rpc.UserFocusHint.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      name_ = "";

      value_ = "";

      hintType_ = 0;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return recommender_rpc.RecommenderRpcProto.internal_static_recommender_rpc_UserFocusHint_descriptor;
    }

    public recommender_rpc.UserFocusHint getDefaultInstanceForType() {
      return recommender_rpc.UserFocusHint.getDefaultInstance();
    }

    public recommender_rpc.UserFocusHint build() {
      recommender_rpc.UserFocusHint result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public recommender_rpc.UserFocusHint buildPartial() {
      recommender_rpc.UserFocusHint result = new recommender_rpc.UserFocusHint(this);
      result.name_ = name_;
      result.value_ = value_;
      result.hintType_ = hintType_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof recommender_rpc.UserFocusHint) {
        return mergeFrom((recommender_rpc.UserFocusHint)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(recommender_rpc.UserFocusHint other) {
      if (other == recommender_rpc.UserFocusHint.getDefaultInstance()) return this;
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        onChanged();
      }
      if (!other.getValue().isEmpty()) {
        value_ = other.value_;
        onChanged();
      }
      if (other.hintType_ != 0) {
        setHintTypeValue(other.getHintTypeValue());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      recommender_rpc.UserFocusHint parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (recommender_rpc.UserFocusHint) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object name_ = "";
    /**
     * <pre>
     * name of the variable, domain, keyword
     * </pre>
     *
     * <code>string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * name of the variable, domain, keyword
     * </pre>
     *
     * <code>string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * name of the variable, domain, keyword
     * </pre>
     *
     * <code>string name = 1;</code>
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * name of the variable, domain, keyword
     * </pre>
     *
     * <code>string name = 1;</code>
     */
    public Builder clearName() {
      
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * name of the variable, domain, keyword
     * </pre>
     *
     * <code>string name = 1;</code>
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      name_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object value_ = "";
    /**
     * <pre>
     * optional, for some cases obsolete
     * </pre>
     *
     * <code>string value = 2;</code>
     */
    public java.lang.String getValue() {
      java.lang.Object ref = value_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        value_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * optional, for some cases obsolete
     * </pre>
     *
     * <code>string value = 2;</code>
     */
    public com.google.protobuf.ByteString
        getValueBytes() {
      java.lang.Object ref = value_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        value_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * optional, for some cases obsolete
     * </pre>
     *
     * <code>string value = 2;</code>
     */
    public Builder setValue(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      value_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * optional, for some cases obsolete
     * </pre>
     *
     * <code>string value = 2;</code>
     */
    public Builder clearValue() {
      
      value_ = getDefaultInstance().getValue();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * optional, for some cases obsolete
     * </pre>
     *
     * <code>string value = 2;</code>
     */
    public Builder setValueBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      value_ = value;
      onChanged();
      return this;
    }

    private int hintType_ = 0;
    /**
     * <code>.recommender_rpc.UserFocusHint.HintType hintType = 3;</code>
     */
    public int getHintTypeValue() {
      return hintType_;
    }
    /**
     * <code>.recommender_rpc.UserFocusHint.HintType hintType = 3;</code>
     */
    public Builder setHintTypeValue(int value) {
      hintType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.recommender_rpc.UserFocusHint.HintType hintType = 3;</code>
     */
    public recommender_rpc.UserFocusHint.HintType getHintType() {
      recommender_rpc.UserFocusHint.HintType result = recommender_rpc.UserFocusHint.HintType.valueOf(hintType_);
      return result == null ? recommender_rpc.UserFocusHint.HintType.UNRECOGNIZED : result;
    }
    /**
     * <code>.recommender_rpc.UserFocusHint.HintType hintType = 3;</code>
     */
    public Builder setHintType(recommender_rpc.UserFocusHint.HintType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      hintType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.recommender_rpc.UserFocusHint.HintType hintType = 3;</code>
     */
    public Builder clearHintType() {
      
      hintType_ = 0;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:recommender_rpc.UserFocusHint)
  }

  // @@protoc_insertion_point(class_scope:recommender_rpc.UserFocusHint)
  private static final recommender_rpc.UserFocusHint DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new recommender_rpc.UserFocusHint();
  }

  public static recommender_rpc.UserFocusHint getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<UserFocusHint>
      PARSER = new com.google.protobuf.AbstractParser<UserFocusHint>() {
    public UserFocusHint parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new UserFocusHint(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<UserFocusHint> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<UserFocusHint> getParserForType() {
    return PARSER;
  }

  public recommender_rpc.UserFocusHint getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

