// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: recom_rpc.proto

package recommender_rpc;

public interface ViewerSelectionStateOrBuilder extends
    // @@protoc_insertion_point(interface_extends:recommender_rpc.ViewerSelectionState)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * is anything marked at all?
   * </pre>
   *
   * <code>bool anySelection = 1;</code>
   */
  boolean getAnySelection();

  /**
   * <pre>
   * If of the variable displayed (selectable) in the viewer
   * </pre>
   *
   * <code>int64 variableIdShown = 2;</code>
   */
  long getVariableIdShown();

  /**
   * <code>int32 rowStart = 3;</code>
   */
  int getRowStart();

  /**
   * <code>int32 rowEnd = 4;</code>
   */
  int getRowEnd();

  /**
   * <pre>
   * is/are a complete row or rows marked?
   * </pre>
   *
   * <code>bool completeRows = 5;</code>
   */
  boolean getCompleteRows();

  /**
   * <code>int32 colStart = 10;</code>
   */
  int getColStart();

  /**
   * <code>int32 colEnd = 11;</code>
   */
  int getColEnd();

  /**
   * <pre>
   * is/are a complete column or columns marked?
   * </pre>
   *
   * <code>bool completeColumns = 12;</code>
   */
  boolean getCompleteColumns();
}
