// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: recom_rpc.proto

package recommender_rpc;

/**
 * <pre>
 * Current "selection" (markings) state of the variable viewer
 * </pre>
 *
 * Protobuf type {@code recommender_rpc.ViewerSelectionState}
 */
public  final class ViewerSelectionState extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:recommender_rpc.ViewerSelectionState)
    ViewerSelectionStateOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ViewerSelectionState.newBuilder() to construct.
  private ViewerSelectionState(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ViewerSelectionState() {
    anySelection_ = false;
    variableIdShown_ = 0L;
    rowStart_ = 0;
    rowEnd_ = 0;
    completeRows_ = false;
    colStart_ = 0;
    colEnd_ = 0;
    completeColumns_ = false;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ViewerSelectionState(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            anySelection_ = input.readBool();
            break;
          }
          case 16: {

            variableIdShown_ = input.readInt64();
            break;
          }
          case 24: {

            rowStart_ = input.readInt32();
            break;
          }
          case 32: {

            rowEnd_ = input.readInt32();
            break;
          }
          case 40: {

            completeRows_ = input.readBool();
            break;
          }
          case 80: {

            colStart_ = input.readInt32();
            break;
          }
          case 88: {

            colEnd_ = input.readInt32();
            break;
          }
          case 96: {

            completeColumns_ = input.readBool();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return recommender_rpc.RecommenderRpcProto.internal_static_recommender_rpc_ViewerSelectionState_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return recommender_rpc.RecommenderRpcProto.internal_static_recommender_rpc_ViewerSelectionState_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            recommender_rpc.ViewerSelectionState.class, recommender_rpc.ViewerSelectionState.Builder.class);
  }

  public static final int ANYSELECTION_FIELD_NUMBER = 1;
  private boolean anySelection_;
  /**
   * <pre>
   * is anything marked at all?
   * </pre>
   *
   * <code>bool anySelection = 1;</code>
   */
  public boolean getAnySelection() {
    return anySelection_;
  }

  public static final int VARIABLEIDSHOWN_FIELD_NUMBER = 2;
  private long variableIdShown_;
  /**
   * <pre>
   * If of the variable displayed (selectable) in the viewer
   * </pre>
   *
   * <code>int64 variableIdShown = 2;</code>
   */
  public long getVariableIdShown() {
    return variableIdShown_;
  }

  public static final int ROWSTART_FIELD_NUMBER = 3;
  private int rowStart_;
  /**
   * <code>int32 rowStart = 3;</code>
   */
  public int getRowStart() {
    return rowStart_;
  }

  public static final int ROWEND_FIELD_NUMBER = 4;
  private int rowEnd_;
  /**
   * <code>int32 rowEnd = 4;</code>
   */
  public int getRowEnd() {
    return rowEnd_;
  }

  public static final int COMPLETEROWS_FIELD_NUMBER = 5;
  private boolean completeRows_;
  /**
   * <pre>
   * is/are a complete row or rows marked?
   * </pre>
   *
   * <code>bool completeRows = 5;</code>
   */
  public boolean getCompleteRows() {
    return completeRows_;
  }

  public static final int COLSTART_FIELD_NUMBER = 10;
  private int colStart_;
  /**
   * <code>int32 colStart = 10;</code>
   */
  public int getColStart() {
    return colStart_;
  }

  public static final int COLEND_FIELD_NUMBER = 11;
  private int colEnd_;
  /**
   * <code>int32 colEnd = 11;</code>
   */
  public int getColEnd() {
    return colEnd_;
  }

  public static final int COMPLETECOLUMNS_FIELD_NUMBER = 12;
  private boolean completeColumns_;
  /**
   * <pre>
   * is/are a complete column or columns marked?
   * </pre>
   *
   * <code>bool completeColumns = 12;</code>
   */
  public boolean getCompleteColumns() {
    return completeColumns_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (anySelection_ != false) {
      output.writeBool(1, anySelection_);
    }
    if (variableIdShown_ != 0L) {
      output.writeInt64(2, variableIdShown_);
    }
    if (rowStart_ != 0) {
      output.writeInt32(3, rowStart_);
    }
    if (rowEnd_ != 0) {
      output.writeInt32(4, rowEnd_);
    }
    if (completeRows_ != false) {
      output.writeBool(5, completeRows_);
    }
    if (colStart_ != 0) {
      output.writeInt32(10, colStart_);
    }
    if (colEnd_ != 0) {
      output.writeInt32(11, colEnd_);
    }
    if (completeColumns_ != false) {
      output.writeBool(12, completeColumns_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (anySelection_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(1, anySelection_);
    }
    if (variableIdShown_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, variableIdShown_);
    }
    if (rowStart_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, rowStart_);
    }
    if (rowEnd_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, rowEnd_);
    }
    if (completeRows_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(5, completeRows_);
    }
    if (colStart_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(10, colStart_);
    }
    if (colEnd_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(11, colEnd_);
    }
    if (completeColumns_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(12, completeColumns_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof recommender_rpc.ViewerSelectionState)) {
      return super.equals(obj);
    }
    recommender_rpc.ViewerSelectionState other = (recommender_rpc.ViewerSelectionState) obj;

    boolean result = true;
    result = result && (getAnySelection()
        == other.getAnySelection());
    result = result && (getVariableIdShown()
        == other.getVariableIdShown());
    result = result && (getRowStart()
        == other.getRowStart());
    result = result && (getRowEnd()
        == other.getRowEnd());
    result = result && (getCompleteRows()
        == other.getCompleteRows());
    result = result && (getColStart()
        == other.getColStart());
    result = result && (getColEnd()
        == other.getColEnd());
    result = result && (getCompleteColumns()
        == other.getCompleteColumns());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ANYSELECTION_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getAnySelection());
    hash = (37 * hash) + VARIABLEIDSHOWN_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getVariableIdShown());
    hash = (37 * hash) + ROWSTART_FIELD_NUMBER;
    hash = (53 * hash) + getRowStart();
    hash = (37 * hash) + ROWEND_FIELD_NUMBER;
    hash = (53 * hash) + getRowEnd();
    hash = (37 * hash) + COMPLETEROWS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getCompleteRows());
    hash = (37 * hash) + COLSTART_FIELD_NUMBER;
    hash = (53 * hash) + getColStart();
    hash = (37 * hash) + COLEND_FIELD_NUMBER;
    hash = (53 * hash) + getColEnd();
    hash = (37 * hash) + COMPLETECOLUMNS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getCompleteColumns());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static recommender_rpc.ViewerSelectionState parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static recommender_rpc.ViewerSelectionState parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static recommender_rpc.ViewerSelectionState parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static recommender_rpc.ViewerSelectionState parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static recommender_rpc.ViewerSelectionState parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static recommender_rpc.ViewerSelectionState parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static recommender_rpc.ViewerSelectionState parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static recommender_rpc.ViewerSelectionState parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static recommender_rpc.ViewerSelectionState parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static recommender_rpc.ViewerSelectionState parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static recommender_rpc.ViewerSelectionState parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static recommender_rpc.ViewerSelectionState parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(recommender_rpc.ViewerSelectionState prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Current "selection" (markings) state of the variable viewer
   * </pre>
   *
   * Protobuf type {@code recommender_rpc.ViewerSelectionState}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:recommender_rpc.ViewerSelectionState)
      recommender_rpc.ViewerSelectionStateOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return recommender_rpc.RecommenderRpcProto.internal_static_recommender_rpc_ViewerSelectionState_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return recommender_rpc.RecommenderRpcProto.internal_static_recommender_rpc_ViewerSelectionState_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              recommender_rpc.ViewerSelectionState.class, recommender_rpc.ViewerSelectionState.Builder.class);
    }

    // Construct using recommender_rpc.ViewerSelectionState.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      anySelection_ = false;

      variableIdShown_ = 0L;

      rowStart_ = 0;

      rowEnd_ = 0;

      completeRows_ = false;

      colStart_ = 0;

      colEnd_ = 0;

      completeColumns_ = false;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return recommender_rpc.RecommenderRpcProto.internal_static_recommender_rpc_ViewerSelectionState_descriptor;
    }

    public recommender_rpc.ViewerSelectionState getDefaultInstanceForType() {
      return recommender_rpc.ViewerSelectionState.getDefaultInstance();
    }

    public recommender_rpc.ViewerSelectionState build() {
      recommender_rpc.ViewerSelectionState result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public recommender_rpc.ViewerSelectionState buildPartial() {
      recommender_rpc.ViewerSelectionState result = new recommender_rpc.ViewerSelectionState(this);
      result.anySelection_ = anySelection_;
      result.variableIdShown_ = variableIdShown_;
      result.rowStart_ = rowStart_;
      result.rowEnd_ = rowEnd_;
      result.completeRows_ = completeRows_;
      result.colStart_ = colStart_;
      result.colEnd_ = colEnd_;
      result.completeColumns_ = completeColumns_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof recommender_rpc.ViewerSelectionState) {
        return mergeFrom((recommender_rpc.ViewerSelectionState)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(recommender_rpc.ViewerSelectionState other) {
      if (other == recommender_rpc.ViewerSelectionState.getDefaultInstance()) return this;
      if (other.getAnySelection() != false) {
        setAnySelection(other.getAnySelection());
      }
      if (other.getVariableIdShown() != 0L) {
        setVariableIdShown(other.getVariableIdShown());
      }
      if (other.getRowStart() != 0) {
        setRowStart(other.getRowStart());
      }
      if (other.getRowEnd() != 0) {
        setRowEnd(other.getRowEnd());
      }
      if (other.getCompleteRows() != false) {
        setCompleteRows(other.getCompleteRows());
      }
      if (other.getColStart() != 0) {
        setColStart(other.getColStart());
      }
      if (other.getColEnd() != 0) {
        setColEnd(other.getColEnd());
      }
      if (other.getCompleteColumns() != false) {
        setCompleteColumns(other.getCompleteColumns());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      recommender_rpc.ViewerSelectionState parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (recommender_rpc.ViewerSelectionState) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private boolean anySelection_ ;
    /**
     * <pre>
     * is anything marked at all?
     * </pre>
     *
     * <code>bool anySelection = 1;</code>
     */
    public boolean getAnySelection() {
      return anySelection_;
    }
    /**
     * <pre>
     * is anything marked at all?
     * </pre>
     *
     * <code>bool anySelection = 1;</code>
     */
    public Builder setAnySelection(boolean value) {
      
      anySelection_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * is anything marked at all?
     * </pre>
     *
     * <code>bool anySelection = 1;</code>
     */
    public Builder clearAnySelection() {
      
      anySelection_ = false;
      onChanged();
      return this;
    }

    private long variableIdShown_ ;
    /**
     * <pre>
     * If of the variable displayed (selectable) in the viewer
     * </pre>
     *
     * <code>int64 variableIdShown = 2;</code>
     */
    public long getVariableIdShown() {
      return variableIdShown_;
    }
    /**
     * <pre>
     * If of the variable displayed (selectable) in the viewer
     * </pre>
     *
     * <code>int64 variableIdShown = 2;</code>
     */
    public Builder setVariableIdShown(long value) {
      
      variableIdShown_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * If of the variable displayed (selectable) in the viewer
     * </pre>
     *
     * <code>int64 variableIdShown = 2;</code>
     */
    public Builder clearVariableIdShown() {
      
      variableIdShown_ = 0L;
      onChanged();
      return this;
    }

    private int rowStart_ ;
    /**
     * <code>int32 rowStart = 3;</code>
     */
    public int getRowStart() {
      return rowStart_;
    }
    /**
     * <code>int32 rowStart = 3;</code>
     */
    public Builder setRowStart(int value) {
      
      rowStart_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 rowStart = 3;</code>
     */
    public Builder clearRowStart() {
      
      rowStart_ = 0;
      onChanged();
      return this;
    }

    private int rowEnd_ ;
    /**
     * <code>int32 rowEnd = 4;</code>
     */
    public int getRowEnd() {
      return rowEnd_;
    }
    /**
     * <code>int32 rowEnd = 4;</code>
     */
    public Builder setRowEnd(int value) {
      
      rowEnd_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 rowEnd = 4;</code>
     */
    public Builder clearRowEnd() {
      
      rowEnd_ = 0;
      onChanged();
      return this;
    }

    private boolean completeRows_ ;
    /**
     * <pre>
     * is/are a complete row or rows marked?
     * </pre>
     *
     * <code>bool completeRows = 5;</code>
     */
    public boolean getCompleteRows() {
      return completeRows_;
    }
    /**
     * <pre>
     * is/are a complete row or rows marked?
     * </pre>
     *
     * <code>bool completeRows = 5;</code>
     */
    public Builder setCompleteRows(boolean value) {
      
      completeRows_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * is/are a complete row or rows marked?
     * </pre>
     *
     * <code>bool completeRows = 5;</code>
     */
    public Builder clearCompleteRows() {
      
      completeRows_ = false;
      onChanged();
      return this;
    }

    private int colStart_ ;
    /**
     * <code>int32 colStart = 10;</code>
     */
    public int getColStart() {
      return colStart_;
    }
    /**
     * <code>int32 colStart = 10;</code>
     */
    public Builder setColStart(int value) {
      
      colStart_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 colStart = 10;</code>
     */
    public Builder clearColStart() {
      
      colStart_ = 0;
      onChanged();
      return this;
    }

    private int colEnd_ ;
    /**
     * <code>int32 colEnd = 11;</code>
     */
    public int getColEnd() {
      return colEnd_;
    }
    /**
     * <code>int32 colEnd = 11;</code>
     */
    public Builder setColEnd(int value) {
      
      colEnd_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 colEnd = 11;</code>
     */
    public Builder clearColEnd() {
      
      colEnd_ = 0;
      onChanged();
      return this;
    }

    private boolean completeColumns_ ;
    /**
     * <pre>
     * is/are a complete column or columns marked?
     * </pre>
     *
     * <code>bool completeColumns = 12;</code>
     */
    public boolean getCompleteColumns() {
      return completeColumns_;
    }
    /**
     * <pre>
     * is/are a complete column or columns marked?
     * </pre>
     *
     * <code>bool completeColumns = 12;</code>
     */
    public Builder setCompleteColumns(boolean value) {
      
      completeColumns_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * is/are a complete column or columns marked?
     * </pre>
     *
     * <code>bool completeColumns = 12;</code>
     */
    public Builder clearCompleteColumns() {
      
      completeColumns_ = false;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:recommender_rpc.ViewerSelectionState)
  }

  // @@protoc_insertion_point(class_scope:recommender_rpc.ViewerSelectionState)
  private static final recommender_rpc.ViewerSelectionState DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new recommender_rpc.ViewerSelectionState();
  }

  public static recommender_rpc.ViewerSelectionState getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ViewerSelectionState>
      PARSER = new com.google.protobuf.AbstractParser<ViewerSelectionState>() {
    public ViewerSelectionState parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ViewerSelectionState(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ViewerSelectionState> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ViewerSelectionState> getParserForType() {
    return PARSER;
  }

  public recommender_rpc.ViewerSelectionState getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

