---
recType: params
recID: py.pd.par.001
group: pandas
name: dataframe
type: DataFrame
vars: dataframe|df|frame
expr: "pyUniqueIterableVariable"
---
recType: params
recID: py.pd.par.002
group: pandas
name: columnNames
type: List
vars: columnNames|names|columns
expr: "pyUniqueIterableVariable"
---
recType: params
recID: py.pd.par.003
group: pandas
name: i
type: Integer
vars: columnNames|names|columns
expr: "collectionElementName"